// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop.money;

import java.math.BigInteger;
import java.time.Duration;
import java.util.Objects;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/// An amount of money.
///
/// @param cents the amount in cents
public record Money(@NonNull BigInteger cents, @Nullable Duration timeout) {

    /// Creates a new `Money`.
    ///
    /// @throws NullPointerException if a required value is `null`
    /// @throws IllegalArgumentException if a value violates its constraints
    public Money {
        Objects.requireNonNull(cents, "cents must not be null");
        if (cents.compareTo(new BigInteger("-1000000000000000000")) < 0) {
            throw new IllegalArgumentException("cents must be at least -1000000000000000000");
        }
    }
}
