// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.Objects;
import java.util.regex.Pattern;
import org.jspecify.annotations.Nullable;

/// A postal address.
///
/// @param street street and house number
public record Address(String street, @Nullable String zip, @Nullable String website, String map) {

    private static final Pattern ZIP_PATTERN = Pattern.compile("^[0-9]{5}$");

    /// Creates a new `Address`.
    ///
    /// @throws NullPointerException if a required value is `null`
    /// @throws IllegalArgumentException if a value violates its constraints
    public Address {
        Objects.requireNonNull(street, "street must not be null");
        if (street.length() < 1) {
            throw new IllegalArgumentException("street must be at least 1 characters long");
        }
        if (street.length() > 80) {
            throw new IllegalArgumentException("street must be at most 80 characters long");
        }
        if (zip != null && !ZIP_PATTERN.matcher(zip).find()) {
            throw new IllegalArgumentException("zip must match the pattern ^[0-9]{5}$");
        }
        if (website != null) {
            try {
                final URI websiteUri = new URI(website);
                if (!websiteUri.isAbsolute() || websiteUri.getHost() == null) {
                    throw new IllegalArgumentException("website must be an absolute URL with a host: " + website);
                }
            } catch (final URISyntaxException e) {
                throw new IllegalArgumentException("website must be a valid URL: " + website, e);
            }
        }
        Objects.requireNonNull(map, "map must not be null");
        try {
            final URI mapUri = new URI(map);
            if (!mapUri.isAbsolute() || mapUri.getHost() == null) {
                throw new IllegalArgumentException("map must be an absolute URL with a host: " + map);
            }
        } catch (final URISyntaxException e) {
            throw new IllegalArgumentException("map must be a valid URL: " + map, e);
        }
    }
}
