// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import java.util.Arrays;
import java.util.Objects;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/// A file attachment.
public record Attachment(
        byte @NonNull [] content,
        byte @Nullable [] checksum,
        double weight,
        @Nullable Integer count) {

    /// Creates a new `Attachment`.
    ///
    /// @throws NullPointerException if a required value is `null`
    /// @throws IllegalArgumentException if a value violates its constraints
    public Attachment {
        Objects.requireNonNull(content, "content must not be null");
        content = content.clone();
        if (content.length < 1) {
            throw new IllegalArgumentException("content must contain at least 1 element(s)");
        }
        checksum = checksum == null ? null : checksum.clone();
    }

    /// Returns a copy of the `content` array.
    @Override
    public byte @NonNull [] content() {
        return content.clone();
    }

    /// Returns a copy of the `checksum` array.
    @Override
    public byte @Nullable [] checksum() {
        return checksum == null ? null : checksum.clone();
    }

    @Override
    public boolean equals(final @Nullable Object obj) {
        return obj instanceof Attachment other
            && Arrays.equals(content, other.content)
            && Arrays.equals(checksum, other.checksum)
            && Double.compare(weight, other.weight) == 0
            && Objects.equals(count, other.count);
    }

    @Override
    public int hashCode() {
        return Objects.hash(Arrays.hashCode(content), Arrays.hashCode(checksum), weight, count);
    }

    @Override
    public String toString() {
        return "Attachment[content=" + "byte[" + content.length + "]" + ", checksum=" + (checksum == null ? "null" : "byte[" + checksum.length + "]") + ", weight=" + weight + ", count=" + count + "]";
    }
}
