// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import java.util.Objects;
import org.jspecify.annotations.Nullable;

/// Neither a record nor its subtype: records cannot be extended.
public class Base {

    private final int a;

    /// Creates a new `Base`.
    public Base(final int a) {
        this.a = a;
    }

    /// Returns the `a`.
    public int a() {
        return a;
    }

    @Override
    public boolean equals(final @Nullable Object obj) {
        if (this == obj) {
            return true;
        }
        return obj instanceof Base other
            && a() == other.a();
    }

    @Override
    public int hashCode() {
        return Objects.hash(a());
    }

    @Override
    public String toString() {
        return "Base[a=" + a()
                + "]";
    }
}
