// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import org.hiero.shop.money.Money;
import org.jspecify.annotations.Nullable;

/// A shopping cart.
///
/// @param items the items in the cart;
///   never more than 100
public record Cart<Item>(
        List<Item> items,
        Set<String> coupons,
        Map<String, String> notes,
        int quantity,
        @Nullable Integer discount,
        boolean legacy,
        Category category,
        Money total) {

    /// Creates a new `Cart`.
    ///
    /// @throws NullPointerException if a required value is `null`
    /// @throws IllegalArgumentException if a value violates its constraints
    public Cart {
        Objects.requireNonNull(items, "items must not be null");
        items = List.copyOf(items);
        if (items.size() < 1) {
            throw new IllegalArgumentException("items must contain at least 1 element(s)");
        }
        if (items.size() > 100) {
            throw new IllegalArgumentException("items must contain at most 100 element(s)");
        }
        Objects.requireNonNull(coupons, "coupons must not be null");
        coupons = Set.copyOf(coupons);
        Objects.requireNonNull(notes, "notes must not be null");
        notes = Map.copyOf(notes);
        if (quantity < 1) {
            throw new IllegalArgumentException("quantity must be at least 1");
        }
        if (quantity > 10) {
            throw new IllegalArgumentException("quantity must be at most 10");
        }
        if (discount != null && discount < 0) {
            throw new IllegalArgumentException("discount must be at least 0");
        }
        Objects.requireNonNull(category, "category must not be null");
        Objects.requireNonNull(total, "total must not be null");
    }

    /// Creates a new `Cart` with the default value of `coupons`, `quantity`.
    public Cart(
            final List<Item> items,
            final Map<String, String> notes,
            final @Nullable Integer discount,
            final boolean legacy,
            final Category category,
            final Money total) {
        this(items, Set.of(), notes, 1, discount, legacy, category, total);
    }

    /// Returns the `legacy` of this value.
    @Override
    @Deprecated
    public boolean legacy() {
        return legacy;
    }

    /// Total price of the cart.
    public Money sum() {
        throw new UnsupportedOperationException("Not implemented yet: Cart.sum");
    }

    public static Cart<String> empty() {
        throw new UnsupportedOperationException("Not implemented yet: Cart.empty");
    }
}
