// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import org.jspecify.annotations.Nullable;

/// A product category.
public enum Category implements Coded {

    /// things to eat
    FOOD((byte) 1, "Food"),
    OTHER((byte) 2, null),
    @Deprecated
    LEGACY((byte) 3, "Legacy \"old\"");

    private final byte code;
    private final @Nullable String label;

    Category(final byte code, final @Nullable String label) {
        this.code = code;
        this.label = label;
    }

    /// Returns the `code` of this value.
    @Override
    public byte code() {
        return code;
    }

    /// Returns the `label` of this value.
    public @Nullable String label() {
        return label;
    }

    /// Whether this category is about food.
    public boolean isFood() {
        throw new UnsupportedOperationException("Not implemented yet: Category.isFood");
    }

    /// @throws java.util.NoSuchElementException
    public static Category byCode(final byte code) {
        throw new UnsupportedOperationException("Not implemented yet: Category.byCode");
    }
}
