// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import java.util.NoSuchElementException;
import org.jspecify.annotations.Nullable;

/// A product category.
public enum Category implements Coded {

    /// things to eat
    FOOD((byte) 1, "Food"),
    OTHER((byte) 2, null),
    /// @deprecated Retained for compatibility; do not use it in new code.
    @Deprecated
    LEGACY((byte) 3, "Legacy \"old\""),
    /// The former catch-all category.
    ///
    /// @deprecated Deprecated because it was never assigned; use `OTHER` instead.
    @Deprecated
    MISC((byte) 4, "Misc");

    private final byte code;
    private final @Nullable String label;

    Category(final byte code, final @Nullable String label) {
        this.code = code;
        this.label = label;
    }

    /// Returns the `code` of this value.
    @Override
    public byte code() {
        return code;
    }

    /// Returns the `label` of this value.
    public @Nullable String label() {
        return label;
    }

    /// Whether this category is about food.
    public boolean isFood() {
        throw new UnsupportedOperationException("Not implemented yet: Category.isFood");
    }

    /// @throws NoSuchElementException if a not found error occurs
    public static Category byCode(final byte code) {
        throw new UnsupportedOperationException("Not implemented yet: Category.byCode");
    }
}
