// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import java.util.Objects;

/// A circle always has a size.
public record Circle(Integer size) implements Shape {

    /// Creates a new `Circle`.
    ///
    /// @throws NullPointerException if a required value is `null`
    public Circle {
        Objects.requireNonNull(size, "size must not be null");
    }
}
