// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import org.jspecify.annotations.Nullable;

/// Something with an id.
public abstract class Entity<Id> {

    private final @Nullable Id id;

    /// Creates a new `Entity`.
    protected Entity(final @Nullable Id id) {
        this.id = id;
    }

    /// Returns the `id`.
    public @Nullable Id id() {
        return id;
    }

    public final <O> boolean sameAs(final Entity<O> other) {
        throw new UnsupportedOperationException("Not implemented yet: Entity.sameAs");
    }
}
