// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

public enum Flag {

    ON(true),
    OFF(false);

    private final boolean default_;

    Flag(final boolean default_) {
        this.default_ = default_;
    }

    /// Returns the `default` of this value.
    public boolean default_() {
        return default_;
    }
}
