// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import java.util.Arrays;
import java.util.Objects;
import org.jspecify.annotations.NonNull;
import org.jspecify.annotations.Nullable;

/// A hash; prints itself.
public record Hash(byte @NonNull [] value) {

    /// Creates a new `Hash`.
    ///
    /// @throws NullPointerException if a required value is `null`
    public Hash {
        Objects.requireNonNull(value, "value must not be null");
        value = value.clone();
    }

    /// Returns a copy of the `value` array.
    @Override
    public byte @NonNull [] value() {
        return value.clone();
    }

    @Override
    public boolean equals(final @Nullable Object obj) {
        return obj instanceof Hash other
            && Arrays.equals(value, other.value);
    }

    @Override
    public int hashCode() {
        return Objects.hash(Arrays.hashCode(value));
    }

    /// Hex representation.
    @Override
    public @NonNull String toString() {
        throw new UnsupportedOperationException("Not implemented yet: Hash.toString");
    }
}
