// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import java.util.concurrent.TimeoutException;
import org.hiero.shop.money.Money;

/// Something with a price.
public interface Priced {

    /// Returns the `price`.
    Money price();

    /// Total including tax.
    ///
    /// @throws PricingException if a pricing error occurs
    /// @throws TimeoutException if a timeout error occurs
    Money gross(final double taxRate) throws TimeoutException;
}
