// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import org.hiero.shop.money.Money;

/// Something with a price.
public interface Priced {

    /// Returns the `price`.
    Money price();

    /// Total including tax.
    Money gross(final double taxRate);
}
