// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

/// Not a record: no attributes.
public class Printer {

    /// Creates a new `Printer`.
    public Printer() {
    }

    public void print() {
        throw new UnsupportedOperationException("Not implemented yet: Printer.print");
    }
}
