// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import java.util.Objects;
import java.util.concurrent.TimeoutException;
import org.hiero.shop.money.Money;
import org.jspecify.annotations.Nullable;

/// A square with a price.
public record Square(@Nullable Integer size, Money price) implements Shape, Priced {

    /// Creates a new `Square`.
    ///
    /// @throws NullPointerException if a required value is `null`
    public Square {
        Objects.requireNonNull(price, "price must not be null");
    }

    /// Total including tax.
    ///
    /// @throws PricingException if a pricing error occurs
    /// @throws TimeoutException if a timeout error occurs
    @Override
    public Money gross(final double taxRate) throws TimeoutException {
        throw new UnsupportedOperationException("Not implemented yet: Square.gross");
    }
}
