// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop.money;

import static org.junit.jupiter.api.Assertions.*;

import java.math.BigInteger;
import java.time.Duration;
import java.util.Arrays;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Money`, generated from the specs.
@DisplayName("Money")
class MoneyTest {

    @Test
    @DisplayName("creates a Money and returns the values")
    void shouldCreateAndReturnTheValues() {
        final BigInteger cents = centsValue();
        final @Nullable Duration timeout = timeoutValue();
        final Money subject = new Money(cents, timeout);
        assertValue(cents, subject.cents());
        assertValue(timeout, subject.timeout());
    }

    @Test
    @DisplayName("rejects null for cents")
    void shouldRejectNullCents() {
        assertThrows(NullPointerException.class, () -> new Money((BigInteger) null, timeoutValue()));
    }

    @Test
    @DisplayName("cents: accepts the minimum (-1000000000000000000)")
    void shouldAcceptCentsAtMinimum() {
        final BigInteger value = new BigInteger("-1000000000000000000");
        final Money subject = new Money(value, timeoutValue());
        assertValue(value, subject.cents());
    }

    @Test
    @DisplayName("cents: accepts the maximum (57896044618658097711785492504343953926634992332820282019728792003956564819967)")
    void shouldAcceptCentsAtMaximum() {
        final BigInteger value = new BigInteger("57896044618658097711785492504343953926634992332820282019728792003956564819967");
        final Money subject = new Money(value, timeoutValue());
        assertValue(value, subject.cents());
    }

    @Test
    @DisplayName("cents: rejects a value below the minimum (-1000000000000000001)")
    void shouldRejectCentsBelowMinimum() {
        assertThrows(IllegalArgumentException.class, () -> new Money(new BigInteger("-1000000000000000001"), timeoutValue()));
    }

    @Test
    @DisplayName("cents: rejects a value above the maximum (57896044618658097711785492504343953926634992332820282019728792003956564819968)")
    void shouldRejectCentsAboveMaximum() {
        assertThrows(IllegalArgumentException.class, () -> new Money(new BigInteger("57896044618658097711785492504343953926634992332820282019728792003956564819968"), timeoutValue()));
    }

    @Test
    @DisplayName("equal values give equal objects and hash codes")
    void shouldCompareByValue() {
        final Money subject = create();
        final Money other = create();
        assertEquals(subject, other);
        assertEquals(subject.hashCode(), other.hashCode());
    }

    private static BigInteger centsValue() {
        return new BigInteger("1");
    }

    private static Duration timeoutValue() {
        return Duration.ofSeconds(1L);
    }

    private static Money create() {
        return new Money(centsValue(), timeoutValue());
    }

    /// Asserts that two values are equal; arrays by their content.
    private static void assertValue(final @Nullable Object expected, final @Nullable Object actual) {
        if (expected instanceof byte[] bytes && actual instanceof byte[] other) {
            assertArrayEquals(bytes, other, () -> "expected " + Arrays.toString(bytes) + " but was " + Arrays.toString(other));
        } else {
            assertEquals(expected, actual);
        }
    }
}
