// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

/// Something with a numeric code.
public interface Coded {

    /// Returns the `code`.
    byte code();
}
