// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

/// Not a record: the attribute is mutable.
public class Counter {

    private int value;

    /// Creates a new `Counter`.
    public Counter(final int value) {
        this.value = value;
    }

    /// Returns the `value`.
    public int value() {
        return value;
    }

    /// Sets the `value`.
    ///
    /// @param value the new value
    /// @return this object
    public Counter setValue(final int value) {
        this.value = value;
        return this;
    }

    @Override
    public String toString() {
        return "Counter[value=" + value()
                + "]";
    }
}
