// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import java.util.Objects;
import org.jspecify.annotations.Nullable;

public class Derived extends Base {

    private final int b;

    /// Creates a new `Derived`.
    public Derived(final int a, final int b) {
        super(a);
        this.b = b;
    }

    /// Returns the `b`.
    public int b() {
        return b;
    }

    @Override
    public boolean equals(final @Nullable Object obj) {
        if (this == obj) {
            return true;
        }
        return obj instanceof Derived other
            && a() == other.a()
            && b() == other.b();
    }

    @Override
    public int hashCode() {
        return Objects.hash(a(), b());
    }

    @Override
    public String toString() {
        return "Derived[a=" + a()
                + ", b=" + b()
                + "]";
    }
}
