// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import org.jspecify.annotations.Nullable;

/// Something with a label that can change.
public abstract class Labelled<Self extends Labelled<Self>> {

    private @Nullable String label;

    /// Creates a new `Labelled`.
    protected Labelled() {
    }

    /// the label, if any
    public @Nullable String label() {
        return label;
    }

    /// Sets the `label`.
    ///
    /// @param label the new value
    /// @return this object
    @SuppressWarnings("unchecked")
    public Self setLabel(final @Nullable String label) {
        this.label = label;
        return (Self) this;
    }
}
