// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import java.util.Objects;

/// Deferred: refers to an abstraction.
public record Listing(Entity<String> entity) {

    /// Creates a new `Listing`.
    ///
    /// @throws NullPointerException if a required value is `null`
    public Listing {
        Objects.requireNonNull(entity, "entity must not be null");
    }
}
