// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import java.io.Serial;
import java.util.Objects;
import org.jspecify.annotations.Nullable;

/// Signals a pricing error.
public final class PricingException extends RuntimeException {

    @Serial
    private static final long serialVersionUID = 1L;

    /// Creates a new `PricingException`.
    ///
    /// @param message the detail message
    /// @param cause   the cause, or `null` if there is none
    /// @throws NullPointerException if `message` is `null`
    public PricingException(final String message, final @Nullable Throwable cause) {
        super(Objects.requireNonNull(message, "message must not be null"), cause);
    }
}
