// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import java.util.List;
import java.util.Objects;
import java.util.concurrent.CompletionStage;
import org.hiero.shop.money.Money;
import org.jspecify.annotations.Nullable;

/// A product.
public final class Product extends Entity<Long> {

    private final String name;
    private final Money price;

    /// Creates a new `Product`.
    ///
    /// @throws NullPointerException if a required value is `null`
    /// @throws IllegalArgumentException if a value violates its constraints
    public Product(final Long id, final String name, final Money price) {
        super(id);
        Objects.requireNonNull(id, "id must not be null");
        Objects.requireNonNull(name, "name must not be null");
        if (name.length() > 40) {
            throw new IllegalArgumentException("name must be at most 40 characters long");
        }
        this.name = name;
        Objects.requireNonNull(price, "price must not be null");
        this.price = price;
    }

    /// Returns the `name`.
    public String name() {
        return name;
    }

    /// Returns the `price`.
    public Money price() {
        return price;
    }

    @Override
    public Long id() {
        return super.id();
    }

    /// The returned stage completes exceptionally with `NoSuchElementException` if the operation fails.
    public CompletionStage<List<Product>> related(final int limit) {
        throw new UnsupportedOperationException("Not implemented yet: Product.related");
    }

    @Override
    public boolean equals(final @Nullable Object obj) {
        if (this == obj) {
            return true;
        }
        return obj instanceof Product other
            && Objects.equals(id(), other.id())
            && Objects.equals(name(), other.name())
            && Objects.equals(price(), other.price());
    }

    @Override
    public int hashCode() {
        return Objects.hash(id(), name(), price());
    }

    @Override
    public String toString() {
        return "Product[id=" + id()
                + ", name=" + name()
                + ", price=" + price()
                + "]";
    }
}
