// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import org.jspecify.annotations.Nullable;

/// A shape; the set of shapes is closed.
public sealed interface Shape permits Circle, Square {

    /// Returns the `size`.
    @Nullable Integer size();

    static Shape unit() {
        throw new UnsupportedOperationException("Not implemented yet: Shape.unit");
    }
}
