// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

/// Constants of the package `org.hiero.shop`.
public final class ShopConstants {

    public static final int MAX_PRODUCTS = 1_000;

    private ShopConstants() {
        throw new UnsupportedOperationException("Constants class cannot be instantiated");
    }
}
