// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

/// Factory methods of the package `org.hiero.shop`.
public final class ShopFactory {

    public static Product create(final String name, final String... tags) {
        throw new UnsupportedOperationException("Not implemented yet: ShopFactory.create");
    }

    private ShopFactory() {
        throw new UnsupportedOperationException("Factory class cannot be instantiated");
    }
}
