package org.hiero.sdk.v3.metalang.generator.go;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.SortedMap;
import java.util.TreeMap;
import org.hiero.sdk.v3.metalang.generator.GeneratedFile;
import org.hiero.sdk.v3.metalang.model.LinkedModel;
import org.hiero.sdk.v3.metalang.model.NamespaceDefinition;
import org.hiero.sdk.v3.metalang.model.QualifiedName;

/**
 * Generates the Go API from the linked model, following {@code guidelines/api-best-practices-go.md}.
 *
 * <p>One Go module holds every namespace; a namespace is a package in a directory per segment. Unlike the Java,
 * TypeScript and Rust generators, a spec folder is not an artifact boundary here — Go has no per-folder unit.
 *
 * <p>This generator is being built up incrementally. It emits the module, one documented package per namespace
 * and the declared types; namespace functions, methods and the generated tests follow. A declaration that has no
 * Go form yet is left out and reported by {@link #deferred()}, so the generated module always compiles.
 */
public final class GoGenerator {

    /** The first line of every generated file. */
    public static final String MARKER = "Generated by metalang from the Hiero SDK V3 specs. Do not edit.";

    /** The header of a generated Go file. */
    static final String HEADER = "// " + MARKER + "\n";

    private final GoGeneratorConfig config;

    /** The declarations the last run left out, with the reason. */
    private final TreeMap<QualifiedName, String> deferred = new TreeMap<>();

    /** Creates a generator with the default configuration. */
    public GoGenerator() {
        this(GoGeneratorConfig.DEFAULT);
    }

    /**
     * Creates a generator.
     *
     * @param config the project-specific configuration
     */
    public GoGenerator(final GoGeneratorConfig config) {
        this.config = Objects.requireNonNull(config, "config must not be null");
    }

    /**
     * Generates the Go module of a model.
     *
     * @param model the linked model
     * @return the generated files, sorted by path
     */
    public List<GeneratedFile> generate(final LinkedModel model) {
        Objects.requireNonNull(model, "model must not be null");
        deferred.clear();
        final GoContext context = new GoContext(model, config);
        final GoNamespaceGenerator namespaces = new GoNamespaceGenerator(context);
        final List<GeneratedFile> files = new ArrayList<>(GoProjectGenerator.module(config));
        for (final NamespaceDefinition namespace : model.namespaces()) {
            files.add(GoProjectGenerator.packageDoc(namespace, config));
            files.addAll(namespaces.generate(namespace.name()));
        }
        deferred.putAll(namespaces.deferred());
        return files.stream().sorted().toList();
    }

    /**
     * The declarations the last {@link #generate(LinkedModel)} left out, with the reason each was left out.
     *
     * @return the deferred declarations, keyed by qualified name
     */
    public SortedMap<QualifiedName, String> deferred() {
        return java.util.Collections.unmodifiableSortedMap(deferred);
    }

    /**
     * The configuration this generator uses.
     *
     * @return the configuration
     */
    public GoGeneratorConfig config() {
        return config;
    }
}
