package org.hiero.sdk.v3.metalang.generator.rust;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.SortedMap;
import java.util.TreeSet;
import org.hiero.sdk.v3.metalang.generator.GeneratedFile;
import org.hiero.sdk.v3.metalang.generator.SpecFolders;
import org.hiero.sdk.v3.metalang.model.LinkedModel;
import org.hiero.sdk.v3.metalang.model.NamespaceDefinition;
import org.hiero.sdk.v3.metalang.model.QualifiedName;
import org.hiero.sdk.v3.metalang.model.TypeDefinition;

/**
 * Generates the Rust API from a {@link LinkedModel}: a Cargo workspace with one crate per spec folder
 * ({@link RustProjectGenerator}), one module per namespace with one private module per type whose items the
 * namespace module re-exports ({@link RustTypeGenerator}, {@link RustNamespaceGenerator}), the support module of the
 * Rust guideline ({@code guidelines/rust-files}) and the tests ({@link RustTestGenerator}). See
 * {@code guidelines/api-best-practices-rust.md} for the mapping. The output is deterministic.
 */
public final class RustGenerator {

    /** Text in the first line of every generated file; it marks the files the generator may replace or delete. */
    public static final String MARKER = "Generated by metalang from the Hiero SDK V3 specs. Do not edit.";

    /** First line of every generated Rust file. */
    static final String HEADER = "// " + MARKER + "\n";

    /** The support files of the guideline, without extension. */
    static final List<String> SUPPORT_FILES = List.of("future", "invalid_argument_error", "stream_item", "url");

    private final RustGeneratorConfig config;

    /** Creates a generator with the default configuration. */
    public RustGenerator() {
        this(RustGeneratorConfig.DEFAULT);
    }

    /**
     * Creates a generator.
     *
     * @param config the project-specific configuration
     */
    public RustGenerator(final RustGeneratorConfig config) {
        this.config = Objects.requireNonNull(config, "config must not be null");
    }

    /**
     * Generates all files.
     *
     * @param model the linked model
     * @return the files, sorted by path
     * @throws org.hiero.sdk.v3.metalang.generator.GenerationException if the specs cannot be mapped to crates
     */
    public List<GeneratedFile> generate(final LinkedModel model) {
        Objects.requireNonNull(model, "model must not be null");
        final RustContext context = new RustContext(config, model);
        final List<GeneratedFile> files = new ArrayList<>();
        for (final SpecFolders.Folder folder : context.folders()) {
            final List<GeneratedFile> crate = new ArrayList<>();
            final List<GeneratedFile> tests = new ArrayList<>();
            for (final NamespaceDefinition namespace : folder.namespaces()) {
                for (final TypeDefinition type : model.types(namespace.name())) {
                    if (context.isGenerated(type.name())) {
                        crate.add(RustTypeGenerator.generate(type, context));
                        RustTestGenerator.generate(type, context).ifPresent(tests::add);
                    }
                }
                RustNamespaceGenerator.functions(namespace.name(), context).ifPresent(f -> {
                    crate.add(f);
                    RustTestGenerator.functions(namespace.name(), context).ifPresent(tests::add);
                });
                RustNamespaceGenerator.constants(namespace.name(), context).ifPresent(crate::add);
                RustNamespaceGenerator.errors(namespace.name(), context).ifPresent(crate::add);
            }
            crate.addAll(RustNamespaceGenerator.modules(folder.name(), crate, context));
            final boolean support = folder.name().equals(context.supportFolder());
            if (support) {
                crate.addAll(support(folder.name()));
            }
            crate.add(RustProjectGenerator.library(folder, support, context));
            crate.addAll(RustTestGenerator.testModules(folder.name(), tests, context));
            crate.addAll(tests);
            crate.add(RustProjectGenerator.manifest(folder, crate, context));
            files.addAll(crate);
        }
        files.addAll(RustProjectGenerator.workspace(context));
        return files.stream().sorted().toList();
    }

    /**
     * Returns the declarations that are not generated yet, with the reason.
     *
     * @param model the linked model
     * @return the deferred declarations, sorted by name
     */
    public SortedMap<QualifiedName, String> deferredTypes(final LinkedModel model) {
        return new RustContext(config, model).deferred();
    }

    private static List<GeneratedFile> support(final String folder) {
        final String directory = RustNames.crateDirectory(folder) + "/src/" + RustNames.SUPPORT;
        final List<GeneratedFile> files = new ArrayList<>();
        final StringBuilder index = new StringBuilder(HEADER)
                .append("//! Types that the generated API uses besides the types of the specs.\n\n");
        final TreeSet<String> exports = new TreeSet<>();
        for (final String name : SUPPORT_FILES) {
            final String source = source(name);
            files.add(new GeneratedFile(directory + "/" + name + ".rs", HEADER + "\n" + source));
            index.append("mod ").append(name).append(";\n");
            final List<String> items = RustNamespaceGenerator.items(source);
            exports.add("pub use " + name + "::" + (items.size() == 1 ? items.getFirst()
                    : "{" + String.join(", ", items) + "}") + ";");
        }
        index.append('\n');
        exports.forEach(e -> index.append(e).append('\n'));
        files.add(new GeneratedFile(directory + "/mod.rs", index.toString()));
        return files;
    }

    /**
     * Returns a support file as it is in the guideline ({@code guidelines/rust-files}).
     *
     * @param name the file name without extension
     * @return the source
     */
    static String source(final String name) {
        try (InputStream in = RustGenerator.class.getResourceAsStream("support/" + name + ".rs")) {
            if (in == null) {
                throw new IllegalStateException("Support file " + name + ".rs is missing; it is copied from "
                        + "guidelines/rust-files by the build");
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (final IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * Assembles a generated Rust file: the header, the imports the code needs, the code.
     *
     * @param path    the path of the file
     * @param imports the imports
     * @param code    the code
     * @return the file
     */
    static GeneratedFile file(final String path, final RustImports imports, final String code) {
        final StringBuilder rs = new StringBuilder(HEADER).append('\n');
        final String block = imports.render(code);
        if (!block.isEmpty()) {
            rs.append(block).append('\n');
        }
        return new GeneratedFile(path, rs.append(code).toString());
    }
}
