// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop.money;

import java.math.BigInteger;
import java.time.Duration;
import java.util.List;
import java.util.Objects;

public enum Plan {

    BASIC(Duration.ofSeconds(30L), new BigInteger("1000"), List.of("a", "b")),
    PREMIUM(Duration.ofSeconds(3_600L), new BigInteger("100000000000000000000"), List.of());

    private final Duration timeout;
    private final BigInteger limit;
    private final List<String> tags;

    Plan(final Duration timeout, final BigInteger limit, final List<String> tags) {
        this.timeout = Objects.requireNonNull(timeout, "timeout must not be null");
        this.limit = Objects.requireNonNull(limit, "limit must not be null");
        this.tags = Objects.requireNonNull(tags, "tags must not be null");
    }

    /// Returns the `timeout` of this value.
    public Duration timeout() {
        return timeout;
    }

    /// Returns the `limit` of this value.
    public BigInteger limit() {
        return limit;
    }

    /// Returns the `tags` of this value.
    public List<String> tags() {
        return tags;
    }
}
