package org.hiero.sdk.v3.metalang.generator.java;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.SortedMap;
import java.util.SortedSet;
import java.util.TreeMap;
import java.util.TreeSet;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.hiero.sdk.v3.metalang.generator.GeneratedFile;
import org.hiero.sdk.v3.metalang.generator.GenerationException;
import org.hiero.sdk.v3.metalang.model.ConstantDefinition;
import org.hiero.sdk.v3.metalang.model.FunctionDefinition;
import org.hiero.sdk.v3.metalang.model.LinkedModel;
import org.hiero.sdk.v3.metalang.model.MethodDefinition;
import org.hiero.sdk.v3.metalang.model.NamespaceDefinition;
import org.hiero.sdk.v3.metalang.model.QualifiedName;
import org.hiero.sdk.v3.metalang.model.Type;
import org.hiero.sdk.v3.metalang.model.TypeDefinition;
import org.hiero.sdk.v3.metalang.semantic.BuiltinType;
import org.jspecify.annotations.Nullable;

/**
 * Generates the Java API from a {@link LinkedModel}.
 *
 * <p>Layout: one JPMS module per spec folder ({@link JavaNames#moduleName(String)}), containing one package per
 * namespace of that folder, built as Maven project with one sub-module (JAR) per JPMS module ({@link MavenGenerator}).
 * Generated: the {@code module-info.java} of every module, the {@code package-info.java}
 * of every package, enums ({@link EnumGenerator}), records ({@link RecordGenerator}), interfaces
 * ({@link InterfaceGenerator}) and classes ({@link ClassGenerator}). Documentation is written as Markdown
 * documentation comments ({@code ///}, Java 23+); the SDK targets Java 25.
 *
 * <p>Which declaration becomes which Java type:
 * <ul>
 *   <li>an enum becomes an {@code enum};</li>
 *   <li>an abstraction with attributes (own or inherited) or with a {@code @@finalMethod} becomes an
 *       {@code abstract class}, the other abstractions become interfaces. An abstraction stays an interface if
 *       the configuration lists it ({@link JavaGeneratorConfig#interfaces()}), if an enum or an interface extends it,
 *       or if a type extends it together with another class (Java has no multiple inheritance of classes; then
 *       <em>none</em> of the involved abstractions becomes a class). The supertypes of an interface are interfaces as
 *       well;</li>
 *   <li>a complex type becomes a {@code record} if it has at least one attribute, all its (effective) attributes are
 *       {@code @@immutable}, it extends no class and no type extends it (records are final and cannot extend
 *       classes); the other complex types become classes.</li>
 * </ul>
 *
 * <p>A type is only generated once every type it refers to (attributes, methods, bounds, the supertypes of an
 * interface or class, the permitted subtypes of a sealed type) is generated as well, and if all its types have a Java
 * mapping — until then it is <em>deferred</em> ({@link #deferredTypes(LinkedModel)}); otherwise the generated modules
 * would not compile. Records, enums and classes implement only the generated interfaces; the other interfaces are
 * written as a comment.
 *
 * <p>The output is deterministic: the same model always produces byte-identical files in the same order.
 */
public final class JavaGenerator {

    /** Text in the first line of every generated file; it marks the files the generator may replace or delete. */
    public static final String MARKER = "Generated by metalang from the Hiero SDK V3 specs. Do not edit.";

    /** First line of every generated Java file. */
    static final String HEADER = "// " + MARKER + "\n";

    /** The JPMS module of the nullness annotations used by the Java mapping. */
    static final String JSPECIFY_MODULE = "org.jspecify";

    private final JavaGeneratorConfig config;

    /**
     * The types to generate and the deferred types with the reason.
     *
     * @param context   the context with the generated types
     * @param deferred  the candidates (types and constants) that are not generated yet, with the reason
     * @param constants the generated constants by namespace
     * @param functions the generated namespace-level functions by namespace
     */
    private record Plan(JavaContext context, SortedMap<QualifiedName, String> deferred,
                        Map<String, List<ConstantDefinition>> constants,
                        Map<String, List<FunctionDefinition>> functions) {
    }

    /** A module: its spec folder, its namespaces and the modules it requires. */
    private record Module(String name, String folder, List<NamespaceDefinition> namespaces, SortedSet<String> requires) {
    }

    /**
     * Creates a generator without project-specific configuration.
     */
    public JavaGenerator() {
        this(JavaGeneratorConfig.DEFAULT);
    }

    /**
     * Creates a generator.
     *
     * @param config the project-specific configuration
     */
    public JavaGenerator(final JavaGeneratorConfig config) {
        this.config = Objects.requireNonNull(config, "config must not be null");
    }

    /**
     * Generates all files for the given model.
     *
     * @param model the linked model (must be free of validation errors)
     * @return the generated files, sorted by path
     * @throws GenerationException if the model cannot be mapped to Java modules (namespace spread over several
     *                             spec folders, spec file outside of a folder, dependency cycle between modules) or
     *                             the configuration does not match the model
     */
    public List<GeneratedFile> generate(final LinkedModel model) {
        Objects.requireNonNull(model, "model must not be null");
        final List<Module> modules = modules(model);
        final Plan plan = plan(model, modules);
        final JavaContext context = plan.context();
        // support files only if a generated declaration uses them
        final Optional<String> threadSafeModule = threadSafeModule(model, modules, context);
        final Optional<String> streamingModule = streamingModule(model, modules, plan);
        final List<GeneratedFile> files = new ArrayList<>();
        final List<FunctionDefinition> allFunctions = plan.functions().values().stream().flatMap(List::stream).toList();
        for (final Module module : modules) {
            final Set<String> packagesWithTypes = new TreeSet<>();
            // the tests of a module can only use the types of the modules it requires
            final Set<String> visible = new HashSet<>(requiredModules(module.name(), modules));
            visible.add(module.name());
            for (final NamespaceDefinition namespace : module.namespaces()) {
                packageInfo(module, namespace).ifPresent(files::add);
                for (final TypeDefinition type : model.types(namespace.name())) {
                    if (context.isGenerated(type.name())) {
                        files.add(generate(module.name(), type, context));
                        TestGenerator.generate(module.name(), type, context, visible, allFunctions)
                                .ifPresent(files::add);
                        packagesWithTypes.add(namespace.name());
                    }
                }
                final List<FunctionDefinition> functions = plan.functions().getOrDefault(namespace.name(), List.of());
                if (!functions.isEmpty()) {
                    files.add(FactoryGenerator.generate(module.name(), namespace.name(), functions, context));
                    files.add(TestGenerator.factory(module.name(), namespace.name(), functions, context, visible,
                            allFunctions));
                    packagesWithTypes.add(namespace.name());
                }
                final List<ConstantDefinition> constants = plan.constants().getOrDefault(namespace.name(), List.of());
                if (!constants.isEmpty()) {
                    files.add(ConstantsGenerator.generate(module.name(), namespace.name(), constants, context));
                    packagesWithTypes.add(namespace.name());
                }
                for (final Map.Entry<String, QualifiedName> function : context.functionInterfaces().names()
                        .entrySet()) {
                    if (function.getValue().namespace().equals(namespace.name())) {
                        files.add(FunctionInterfaceGenerator.generate(module.name(), function.getValue(),
                                context.functionInterfaces().types().get(function.getKey()), context));
                        packagesWithTypes.add(namespace.name());
                    }
                }
                for (final Map.Entry<String, QualifiedName> exception : context.exceptions().entrySet()) {
                    if (exception.getValue().namespace().equals(namespace.name())) {
                        files.add(ExceptionGenerator.generate(module.name(), exception.getKey(), exception.getValue()));
                        packagesWithTypes.add(namespace.name());
                    }
                }
            }
            // the support files of the guideline (guidelines/java-files), in the module all their users require
            final List<String> supportPackages = new ArrayList<>();
            if (threadSafeModule.filter(module.name()::equals).isPresent()) {
                files.add(ThreadSafeGenerator.generate(module.name()));
                supportPackages.add(ThreadSafeGenerator.PACKAGE);
            }
            if (streamingModule.filter(module.name()::equals).isPresent()) {
                SupportFiles.STREAMING.forEach(name -> files.add(SupportFiles.generate(module.name(), name)));
                supportPackages.add(SupportFiles.STREAMING_PACKAGE);
            }
            files.add(moduleInfo(module, packagesWithTypes, supportPackages.stream().sorted().toList()));
        }
        // the Maven build: one sub-module (and JAR) per JPMS module
        final Map<String, String> folderOf = new HashMap<>();
        modules.forEach(m -> folderOf.put(m.name(), m.folder()));
        final List<MavenGenerator.MavenModule> mavenModules = modules.stream()
                .map(m -> new MavenGenerator.MavenModule(m.name(), MavenGenerator.artifactId(m.folder()), m.folder(),
                        m.requires().stream().map(r -> MavenGenerator.artifactId(folderOf.get(r))).toList()))
                .toList();
        files.add(MavenGenerator.parent(mavenModules, config));
        mavenModules.forEach(m -> files.add(MavenGenerator.module(m, config)));
        return files.stream().sorted().toList();
    }

    /**
     * Returns the types that could be generated but are not generated yet, with the reason (a referenced type that
     * is not generated yet, or a type without Java mapping).
     *
     * @param model the linked model
     * @return the deferred types and the reasons, sorted by name
     * @throws GenerationException if the model cannot be mapped to Java modules
     */
    public SortedMap<QualifiedName, String> deferredTypes(final LinkedModel model) {
        Objects.requireNonNull(model, "model must not be null");
        return plan(model, modules(model)).deferred();
    }

    private static GeneratedFile generate(final String module, final TypeDefinition type, final JavaContext context) {
        return switch (type) {
            case TypeDefinition.EnumDefinition enumType -> EnumGenerator.generate(module, enumType, context);
            case TypeDefinition.ComplexTypeDefinition complex when context.isClass(complex.name()) ->
                    ClassGenerator.generate(module, complex, context);
            case TypeDefinition.ComplexTypeDefinition complex when complex.abstraction() ->
                    InterfaceGenerator.generate(module, complex, context);
            case TypeDefinition.ComplexTypeDefinition complex -> RecordGenerator.generate(module, complex, context);
        };
    }

    /**
     * Classifies the types and then removes the candidates that cannot be generated until nothing changes (a
     * greatest fixed point, so types that refer to each other are generated together).
     */
    private Plan plan(final LinkedModel model, final List<Module> modules) {
        final Map<String, String> moduleOfNamespace = new HashMap<>();
        modules.forEach(m -> m.namespaces().forEach(n -> moduleOfNamespace.put(n.name(), m.name())));
        final Map<String, QualifiedName> exceptions = exceptions(model, modules, moduleOfNamespace);
        final FunctionInterfaces functionInterfaces = functionInterfaces(model, modules, moduleOfNamespace,
                exceptions);
        final Set<QualifiedName> abstractClasses = abstractClasses(model);
        final Set<QualifiedName> extended = extendedTypes(model);
        final Set<QualifiedName> classes = new HashSet<>(abstractClasses);
        final SortedMap<QualifiedName, TypeDefinition> candidates = new TreeMap<>();
        for (final TypeDefinition type : model.types()) {
            if (!moduleOfNamespace.containsKey(type.name().namespace())) {
                continue;
            }
            if (type instanceof TypeDefinition.ComplexTypeDefinition complex && !complex.abstraction()
                    && !isRecord(complex, extended, abstractClasses, model)) {
                classes.add(type.name());
            }
            candidates.put(type.name(), type);
        }
        final SortedMap<QualifiedName, String> deferred = new TreeMap<>();
        boolean changed = true;
        while (changed) {
            changed = false;
            final JavaContext context = new JavaContext(model, candidates.keySet(), moduleOfNamespace, classes,
                    exceptions, functionInterfaces);
            for (final TypeDefinition type : List.copyOf(candidates.values())) {
                final Optional<String> reason = missingType(type, context)
                        .or(() -> unsupported(type, context));
                if (reason.isPresent()) {
                    candidates.remove(type.name());
                    deferred.put(type.name(), reason.get());
                    changed = true;
                }
            }
        }
        final JavaContext context = new JavaContext(model, candidates.keySet(), moduleOfNamespace, classes,
                exceptions, functionInterfaces);
        return new Plan(context, deferred, constants(model, moduleOfNamespace, context, deferred),
                functions(model, moduleOfNamespace, context, deferred));
    }

    /**
     * The namespace-level functions that can be generated, by namespace (static methods of the factory class). A
     * function that refers to a type that is not generated, or whose types have no Java form, is deferred on its own;
     * deferred functions are reported as {@code namespace.name(parameter types)}.
     */
    private static Map<String, List<FunctionDefinition>> functions(final LinkedModel model,
                                                                   final Map<String, String> moduleOfNamespace,
                                                                   final JavaContext context,
                                                                   final SortedMap<QualifiedName, String> deferred) {
        final Map<String, List<FunctionDefinition>> functions = new TreeMap<>();
        for (final FunctionDefinition function : model.functions()) {
            final String namespace = function.namespace();
            if (!moduleOfNamespace.containsKey(namespace)) {
                continue;
            }
            final QualifiedName holder = new QualifiedName(namespace, FactoryGenerator.className(namespace));
            final MethodDefinition method = function.method();
            final Set<QualifiedName> used = new TreeSet<>();
            method.typeParameters().forEach(p -> referencedTypes(p.bound(), used));
            referencedTypes(method.returnType(), used);
            method.parameters().forEach(p -> referencedTypes(p.type(), used));
            Optional<String> reason = model.type(holder).isPresent()
                    ? Optional.of("the factory class " + holder + " clashes with a type of the same name")
                    : used.stream().filter(n -> !context.isGenerated(n)).findFirst()
                    .map(n -> "refers to " + n + " (" + kind(context, n) + ", not generated yet)");
            if (reason.isEmpty()) {
                try {
                    FactoryGenerator.function(function, context.imports(JavaNames.packageName(namespace),
                            holder.name()), context);
                } catch (final JavaTypes.UnsupportedTypeException e) {
                    reason = Optional.of(e.getMessage());
                }
            }
            if (reason.isPresent()) {
                deferred.put(new QualifiedName(namespace, method.signature().replace(namespace + ".", "")),
                        reason.get());
            } else {
                functions.computeIfAbsent(namespace, k -> new ArrayList<>()).add(function);
            }
        }
        return functions;
    }

    /**
     * The constants that can be generated, by namespace. A constant whose type is not generated or whose value has no
     * Java form is deferred; the other constants of its namespace are generated anyway.
     */
    private static Map<String, List<ConstantDefinition>> constants(final LinkedModel model,
                                                                   final Map<String, String> moduleOfNamespace,
                                                                   final JavaContext context,
                                                                   final SortedMap<QualifiedName, String> deferred) {
        final Map<String, List<ConstantDefinition>> constants = new TreeMap<>();
        for (final ConstantDefinition constant : model.constants()) {
            final String namespace = constant.name().namespace();
            if (!moduleOfNamespace.containsKey(namespace)) {
                continue;
            }
            final QualifiedName holder = new QualifiedName(namespace, ConstantsGenerator.className(namespace));
            final Set<QualifiedName> used = new TreeSet<>();
            referencedTypes(constant.type(), used);
            Optional<String> reason = model.type(holder).isPresent()
                    ? Optional.of("the constants class " + holder + " clashes with a type of the same name")
                    : used.stream().filter(n -> !context.isGenerated(n)).findFirst()
                    .map(n -> "refers to " + n + " (" + kind(context, n) + ", not generated yet)");
            if (reason.isEmpty()) {
                try {
                    ConstantsGenerator.constant(constant, context.imports(JavaNames.packageName(namespace),
                            holder.name()), context);
                } catch (final JavaTypes.UnsupportedTypeException e) {
                    reason = Optional.of(e.getMessage());
                }
            }
            if (reason.isPresent()) {
                deferred.put(constant.name(), reason.get());
            } else {
                constants.computeIfAbsent(namespace, k -> new ArrayList<>()).add(constant);
            }
        }
        return constants;
    }

    /**
     * Places the exception class of every error identifier without standard exception: in the package of a namespace
     * that uses the identifier and whose module all other using modules require (directly or transitively), so that
     * every use can see it; among several such namespaces the shortest name wins ({@code enterprise.service} before
     * {@code enterprise.service.account}).
     */
    private static Map<String, QualifiedName> exceptions(final LinkedModel model, final List<Module> modules,
                                                         final Map<String, String> moduleOfNamespace) {
        final Map<String, Set<String>> usage = new TreeMap<>();
        for (final TypeDefinition type : model.types()) {
            type.declaredMethods().forEach(m -> errorIds(m).forEach(id -> usage.computeIfAbsent(id,
                    k -> new TreeSet<>()).add(type.name().namespace())));
        }
        for (final FunctionDefinition function : model.functions()) {
            errorIds(function.method()).forEach(id -> usage.computeIfAbsent(id, k -> new TreeSet<>())
                    .add(function.namespace()));
        }
        final Map<String, Set<String>> required = new HashMap<>();
        modules.forEach(m -> required.put(m.name(), requiredModules(m.name(), modules)));
        final Map<String, QualifiedName> exceptions = new TreeMap<>();
        final List<String> problems = new ArrayList<>();
        usage.forEach((errorId, namespaces) -> {
            if (JavaExceptions.standard(errorId).isPresent()) {
                return;
            }
            final List<String> used = namespaces.stream().filter(moduleOfNamespace::containsKey).toList();
            final Set<String> usedModules = used.stream().map(moduleOfNamespace::get)
                    .collect(Collectors.toCollection(TreeSet::new));
            final Optional<String> home = home(used, moduleOfNamespace, required);
            if (home.isEmpty()) {
                if (!used.isEmpty()) {
                    problems.add("Error '" + errorId + "' is used in the modules " + usedModules
                            + ", but none of them is required by all others; its exception class has no home");
                }
                return;
            }
            final QualifiedName name = new QualifiedName(home.get(), JavaExceptions.className(errorId));
            if (model.type(name).isPresent()) {
                problems.add("The exception class of error '" + errorId + "' clashes with the type " + name);
            }
            exceptions.put(errorId, name);
        });
        if (!problems.isEmpty()) {
            throw new GenerationException(problems);
        }
        return exceptions;
    }

    /**
     * The namespace for a declaration that several namespaces use: one of them whose module all other using modules
     * require (so every use can see it), the shortest name first.
     */
    private static Optional<String> home(final List<String> used, final Map<String, String> moduleOfNamespace,
                                         final Map<String, Set<String>> required) {
        final Set<String> usedModules = used.stream().map(moduleOfNamespace::get).collect(Collectors.toSet());
        return used.stream()
                .filter(n -> usedModules.stream().allMatch(m -> m.equals(moduleOfNamespace.get(n))
                        || required.get(m).contains(moduleOfNamespace.get(n))))
                .min(java.util.Comparator.comparing(String::length).thenComparing(n -> n));
    }

    /**
     * The module that contains the {@code @ThreadSafe} annotation: see {@link #supportModule}.
     */
    private static Optional<String> threadSafeModule(final LinkedModel model, final List<Module> modules,
                                                     final JavaContext context) {
        final Set<String> namespaces = new TreeSet<>();
        for (final TypeDefinition type : model.types()) {
            if (!context.isGenerated(type.name())) {
                continue;
            }
            final boolean used = type.hasAnnotation("threadSafe")
                    || type.declaredMethods().stream().anyMatch(m -> m.hasAnnotation("threadSafe"))
                    || (type instanceof TypeDefinition.ComplexTypeDefinition complex
                    && complex.declaredFields().stream().anyMatch(f -> f.hasAnnotation("threadSafe")));
            if (used) {
                namespaces.add(type.name().namespace());
            }
        }
        return supportModule("@@threadSafe", "the @ThreadSafe annotation", namespaces, modules);
    }

    /**
     * The module that contains the streaming support ({@code HieroStream}, {@code StreamItem}, ...): see
     * {@link #supportModule}. Used by {@code @@streaming} methods and {@code streamResult<T>} types.
     */
    private static Optional<String> streamingModule(final LinkedModel model, final List<Module> modules,
                                                    final Plan plan) {
        final Set<String> namespaces = new TreeSet<>();
        for (final TypeDefinition type : model.types()) {
            if (!plan.context().isGenerated(type.name())) {
                continue;
            }
            final List<Type> types = new ArrayList<>();
            type.fields().forEach(f -> types.add(f.type()));
            boolean streaming = false;
            for (final MethodDefinition method : type.declaredMethods()) {
                streaming |= method.hasAnnotation("streaming");
                types.add(method.returnType());
                method.parameters().forEach(p -> types.add(p.type()));
            }
            if (streaming || types.stream().anyMatch(JavaGenerator::containsStreamResult)) {
                namespaces.add(type.name().namespace());
            }
        }
        for (final FunctionDefinition function : plan.functions().values().stream().flatMap(List::stream).toList()) {
            final MethodDefinition method = function.method();
            if (method.hasAnnotation("streaming") || containsStreamResult(method.returnType())
                    || method.parameters().stream().anyMatch(p -> containsStreamResult(p.type()))) {
                namespaces.add(function.namespace());
            }
        }
        plan.constants().values().stream().flatMap(List::stream).filter(c -> containsStreamResult(c.type()))
                .forEach(c -> namespaces.add(c.name().namespace()));
        return supportModule("@@streaming / streamResult", "the streaming support", namespaces, modules);
    }

    private static boolean containsStreamResult(final @Nullable Type type) {
        return switch (type) {
            case null -> false;
            case Type.BasicType basic -> basic.builtin().category() == BuiltinType.Category.STREAM_RESULT
                    || basic.arguments().stream().anyMatch(JavaGenerator::containsStreamResult);
            case Type.DeclaredType declared -> declared.arguments().stream().anyMatch(JavaGenerator::containsStreamResult);
            case Type.FunctionType function -> containsStreamResult(function.returnType())
                    || function.parameters().stream().anyMatch(p -> containsStreamResult(p.type()));
            case Type.WildcardType wildcard -> containsStreamResult(wildcard.upperBound());
            default -> false;
        };
    }

    /**
     * The module that contains a group of support files (guidelines/java-files). It is the base module that all other
     * modules require, so that the support packages never move when another module starts to use them; without such
     * a module, one of the using modules that all other using modules require. Empty if nobody uses the support.
     *
     * @throws GenerationException if there is neither a base module nor a using module required by all others
     */
    private static Optional<String> supportModule(final String feature, final String support,
                                                  final Set<String> namespaces, final List<Module> modules) {
        final Map<String, String> moduleOfNamespace = new HashMap<>();
        modules.forEach(m -> m.namespaces().forEach(n -> moduleOfNamespace.put(n.name(), m.name())));
        final List<String> used = namespaces.stream().filter(moduleOfNamespace::containsKey).toList();
        if (used.isEmpty()) {
            return Optional.empty();
        }
        final Map<String, Set<String>> required = new HashMap<>();
        modules.forEach(m -> required.put(m.name(), requiredModules(m.name(), modules)));
        final Optional<String> base = modules.stream().map(Module::name)
                .filter(candidate -> modules.stream().allMatch(m -> m.name().equals(candidate)
                        || required.get(m.name()).contains(candidate)))
                .findFirst();
        if (base.isPresent()) {
            return base;
        }
        return home(used, moduleOfNamespace, required).map(moduleOfNamespace::get)
                .or(() -> {
                    throw new GenerationException(List.of(feature + " is used in the modules "
                            + used.stream().map(moduleOfNamespace::get).collect(Collectors.toCollection(TreeSet::new))
                            + ", but none of them is required by all others; " + support + " has no home"));
                });
    }

    /**
     * Places the {@code @FunctionalInterface} of every function type that no {@code java.util.function} interface
     * matches, like the exception classes: one interface per function type, in a using namespace that all users can
     * see. A function type without home, with type variables, or whose interface name clashes with a type, an
     * exception class or the interface of another function type gets no interface; the declarations that use it are
     * deferred with that reason.
     */
    private static FunctionInterfaces functionInterfaces(final LinkedModel model, final List<Module> modules,
                                                         final Map<String, String> moduleOfNamespace,
                                                         final Map<String, QualifiedName> exceptions) {
        final Map<String, Type.FunctionType> types = new TreeMap<>();
        final Map<String, Set<String>> usage = new TreeMap<>();
        final java.util.function.BiConsumer<Type, String> collect = (type, namespace) -> functionTypes(type, f -> {
            if (!JavaTypes.isStandard(f)) {
                types.putIfAbsent(f.text(), f);
                usage.computeIfAbsent(f.text(), k -> new TreeSet<>()).add(namespace);
            }
        });
        for (final TypeDefinition type : model.types()) {
            final String namespace = type.name().namespace();
            type.typeParameters().forEach(p -> collect.accept(p.bound(), namespace));
            type.fields().forEach(f -> collect.accept(f.type(), namespace));
            for (final MethodDefinition method : type.declaredMethods()) {
                method.typeParameters().forEach(p -> collect.accept(p.bound(), namespace));
                collect.accept(method.returnType(), namespace);
                method.parameters().forEach(p -> collect.accept(p.type(), namespace));
            }
        }
        for (final FunctionDefinition function : model.functions()) {
            final MethodDefinition method = function.method();
            collect.accept(method.returnType(), function.namespace());
            method.parameters().forEach(p -> collect.accept(p.type(), function.namespace()));
        }
        model.constants().forEach(c -> collect.accept(c.type(), c.name().namespace()));
        final Map<String, Set<String>> required = new HashMap<>();
        modules.forEach(m -> required.put(m.name(), requiredModules(m.name(), modules)));
        final Map<String, QualifiedName> names = new TreeMap<>();
        final Map<String, String> problems = new TreeMap<>();
        usage.forEach((text, namespaces) -> {
            final List<String> used = namespaces.stream().filter(moduleOfNamespace::containsKey).toList();
            if (containsTypeVariable(types.get(text))) {
                problems.put(text, "Function type '" + text + "' needs its own functional interface, which cannot "
                        + "use type variables (only function types with at most two parameters can)");
                return;
            }
            final Optional<String> home = home(used, moduleOfNamespace, required);
            if (home.isEmpty()) {
                problems.put(text, "Function type '" + text + "' is used in modules of which none is required by all "
                        + "others; its functional interface has no home");
                return;
            }
            names.put(text, new QualifiedName(home.get(), FunctionInterfaceGenerator.className(types.get(text))));
        });
        // a name may be used only once: by one function type, and not by a type or an exception class
        final Map<QualifiedName, List<String>> byName = new TreeMap<>();
        names.forEach((text, name) -> byName.computeIfAbsent(name, k -> new ArrayList<>()).add(text));
        byName.forEach((name, texts) -> {
            final boolean clash = texts.size() > 1 || model.type(name).isPresent()
                    || exceptions.containsValue(name);
            if (clash) {
                texts.forEach(text -> {
                    names.remove(text);
                    problems.put(text, "The functional interface " + name + " of function type '" + text
                            + "' clashes with " + (texts.size() > 1 ? "the interface of another function type"
                            : "a type of the same name"));
                });
            }
        });
        types.keySet().retainAll(names.keySet());
        return new FunctionInterfaces(names, types, problems);
    }

    /** Calls {@code sink} for every function type in {@code type}, including nested ones. */
    private static void functionTypes(final @Nullable Type type,
                                      final java.util.function.Consumer<Type.FunctionType> sink) {
        switch (type) {
            case null -> {
            }
            case Type.FunctionType function -> {
                sink.accept(function);
                functionTypes(function.returnType(), sink);
                function.parameters().forEach(p -> functionTypes(p.type(), sink));
            }
            case Type.DeclaredType declared -> declared.arguments().forEach(a -> functionTypes(a, sink));
            case Type.BasicType basic -> basic.arguments().forEach(a -> functionTypes(a, sink));
            case Type.WildcardType wildcard -> functionTypes(wildcard.upperBound(), sink);
            default -> {
            }
        }
    }

    private static boolean containsTypeVariable(final @Nullable Type type) {
        return switch (type) {
            case null -> false;
            case Type.TypeVariable ignored -> true;
            case Type.FunctionType function -> containsTypeVariable(function.returnType())
                    || function.parameters().stream().anyMatch(p -> containsTypeVariable(p.type()));
            case Type.DeclaredType declared -> declared.arguments().stream().anyMatch(JavaGenerator::containsTypeVariable);
            case Type.BasicType basic -> basic.arguments().stream().anyMatch(JavaGenerator::containsTypeVariable);
            case Type.WildcardType wildcard -> containsTypeVariable(wildcard.upperBound());
            default -> false;
        };
    }

    private static List<String> errorIds(final MethodDefinition method) {
        return method.annotation("throws").stream().flatMap(a -> a.arguments().stream()).map(a -> a.text()).toList();
    }

    /** The modules a module requires, directly or transitively. */
    private static Set<String> requiredModules(final String module, final List<Module> modules) {
        final Map<String, SortedSet<String>> edges = new HashMap<>();
        modules.forEach(m -> edges.put(m.name(), m.requires()));
        final Set<String> result = new TreeSet<>();
        final List<String> pending = new ArrayList<>(edges.getOrDefault(module, new TreeSet<>()));
        while (!pending.isEmpty()) {
            final String next = pending.removeLast();
            if (result.add(next)) {
                pending.addAll(edges.getOrDefault(next, new TreeSet<>()));
            }
        }
        return result;
    }

    /**
     * Decides which abstractions become abstract classes: those with attributes or a {@code @@finalMethod}, except
     * the configured interfaces, the ones an enum or an interface extends, and the ones that a type extends together
     * with another class. An interface needs interfaces as supertypes, so the decision is propagated upwards until
     * nothing changes.
     */
    private Set<QualifiedName> abstractClasses(final LinkedModel model) {
        final List<String> problems = new ArrayList<>();
        for (final QualifiedName name : new TreeSet<>(config.interfaces())) {
            final Optional<TypeDefinition> type = model.type(name);
            if (type.isEmpty()) {
                problems.add(JavaGeneratorConfig.INTERFACES + ": unknown type " + name);
            } else if (!(type.get() instanceof TypeDefinition.ComplexTypeDefinition c && c.abstraction())) {
                problems.add(JavaGeneratorConfig.INTERFACES + ": " + name + " is no abstraction");
            } else if (hasFinalMethod(type.get())) {
                problems.add(JavaGeneratorConfig.INTERFACES + ": " + name
                        + " has a @@finalMethod and must be an abstract class");
            }
        }
        if (!problems.isEmpty()) {
            throw new GenerationException(problems);
        }
        final Set<QualifiedName> classes = new HashSet<>();
        for (final TypeDefinition type : model.types()) {
            if (isAbstraction(type) && (!type.fields().isEmpty() || hasFinalMethod(type))
                    && !config.interfaces().contains(type.name())) {
                classes.add(type.name());
            }
        }
        boolean changed = true;
        while (changed) {
            final Set<QualifiedName> interfaces = new HashSet<>();
            for (final TypeDefinition type : model.types()) {
                final List<QualifiedName> classSupertypes = new ArrayList<>();
                int concreteSupertypes = 0;
                for (final Type.DeclaredType supertype : declaredSupertypes(type)) {
                    if (classes.contains(supertype.name())) {
                        classSupertypes.add(supertype.name());
                    } else if (model.type(supertype.name()).filter(t -> !isAbstraction(t)).isPresent()) {
                        concreteSupertypes++;
                    }
                }
                final boolean isInterface = isAbstraction(type) && !classes.contains(type.name());
                if (type instanceof TypeDefinition.EnumDefinition || isInterface
                        || classSupertypes.size() + concreteSupertypes > 1) {
                    interfaces.addAll(classSupertypes);
                }
            }
            // the supertypes of an interface are interfaces; a @@finalMethod keeps its abstraction a class
            final List<QualifiedName> pending = new ArrayList<>(interfaces);
            while (!pending.isEmpty()) {
                model.type(pending.removeLast()).ifPresent(t -> declaredSupertypes(t).stream()
                        .map(Type.DeclaredType::name)
                        .filter(classes::contains)
                        .filter(interfaces::add)
                        .forEach(pending::add));
            }
            interfaces.removeIf(n -> model.type(n).map(JavaGenerator::hasFinalMethod).orElse(false));
            changed = classes.removeAll(interfaces);
        }
        return classes;
    }

    private static boolean isAbstraction(final TypeDefinition type) {
        return type instanceof TypeDefinition.ComplexTypeDefinition complex && complex.abstraction();
    }

    private static List<Type.DeclaredType> declaredSupertypes(final TypeDefinition type) {
        return type.supertypes().stream().filter(Type.DeclaredType.class::isInstance)
                .map(Type.DeclaredType.class::cast).toList();
    }

    /** The types that another type extends; only the supertype itself, not its type arguments. */
    private static Set<QualifiedName> extendedTypes(final LinkedModel model) {
        final Set<QualifiedName> extended = new HashSet<>();
        for (final TypeDefinition type : model.types()) {
            declaredSupertypes(type).forEach(t -> extended.add(t.name()));
        }
        return extended;
    }

    private static boolean hasFinalMethod(final TypeDefinition type) {
        return type.methods().stream().anyMatch(m -> m.hasAnnotation("finalMethod"));
    }

    private static boolean isRecord(final TypeDefinition.ComplexTypeDefinition type, final Set<QualifiedName> extended,
                                    final Set<QualifiedName> abstractClasses, final LinkedModel model) {
        return !type.abstraction()
                && !type.fields().isEmpty()
                && type.fields().stream().allMatch(f -> f.hasAnnotation("immutable"))
                && !extended.contains(type.name())
                // a record cannot extend a class (a concrete type or an abstraction that becomes an abstract class)
                && declaredSupertypes(type).stream().noneMatch(s -> abstractClasses.contains(s.name())
                || model.definition(s) instanceof TypeDefinition.ComplexTypeDefinition c && !c.abstraction());
    }

    /** The first reason why the candidate cannot be generated with the current set of generated types. */
    private static Optional<String> missingType(final TypeDefinition type, final JavaContext context) {
        final List<QualifiedName> classSupertypes = declaredSupertypes(type).stream().map(Type.DeclaredType::name)
                .filter(context::isClass).toList();
        if (classSupertypes.size() > 1) {
            // only possible with @@finalMethod abstractions, which cannot become interfaces
            return Optional.of("extends the classes " + classSupertypes + "; Java has no multiple inheritance");
        }
        if (!classSupertypes.isEmpty() && !context.isClass(type.name())) {
            return Optional.of((type instanceof TypeDefinition.EnumDefinition ? "an enum" : "an interface")
                    + " cannot extend the class " + classSupertypes.getFirst());
        }
        final Optional<String> covariantAsync = covariantAsyncOverride(type, context.model());
        if (covariantAsync.isPresent()) {
            return covariantAsync;
        }
        final Set<QualifiedName> used = new TreeSet<>();
        type.typeParameters().forEach(p -> referencedTypes(p.bound(), used));
        type.fields().forEach(f -> referencedTypes(f.type(), used));
        for (final MethodDefinition method : type.methods()) {
            method.typeParameters().forEach(p -> referencedTypes(p.bound(), used));
            referencedTypes(method.returnType(), used);
            method.parameters().forEach(p -> referencedTypes(p.type(), used));
        }
        if (type instanceof TypeDefinition.EnumDefinition enumType) {
            enumType.attributes().forEach(a -> referencedTypes(a.type(), used));
        }
        // a class cannot leave out its superclass (constructor, inherited state)
        declaredSupertypes(type).stream().filter(s -> context.isClass(s.name())).forEach(s -> referencedTypes(s, used));
        if (isAbstraction(type)) {
            if (!context.isClass(type.name())) {
                // an interface cannot leave out its supertypes: implementations would miss their members
                type.supertypes().forEach(s -> referencedTypes(s, used));
                for (final Type.DeclaredType supertype : declaredSupertypes(type)) {
                    if (context.model().type(supertype.name()).filter(t -> !isAbstraction(t)).isPresent()) {
                        return Optional.of("extends " + supertype.name() + ", which is no abstraction");
                    }
                }
            }
            for (final QualifiedName permitted : InterfaceGenerator.permittedSubtypes(type)) {
                if (!context.isGenerated(permitted)) {
                    return Optional.of("permits " + permitted + " (" + kind(context, permitted)
                            + ", not generated yet)");
                }
                if (!context.module(permitted.namespace()).equals(context.module(type.name().namespace()))) {
                    return Optional.of("permits " + permitted + ", which is in another Java module");
                }
            }
        }
        return used.stream()
                .filter(n -> !n.equals(type.name()) && !context.isGenerated(n))
                .findFirst()
                .map(n -> "refers to " + n + " (" + kind(context, n) + ", not generated yet)");
    }

    /**
     * Finds an {@code @@async} method that overrides an inherited one with another return type. The meta-language
     * allows a covariant return type, but {@code CompletionStage<T>} is invariant in Java, so the override does not
     * compile ({@code CompletionStage<PaidQueryResponse<R>>} is no {@code CompletionStage<QueryResponse<R>>}).
     */
    private static Optional<String> covariantAsyncOverride(final TypeDefinition type, final LinkedModel model) {
        for (final MethodDefinition method : type.declaredMethods()) {
            if (method.isStatic() || !method.hasAnnotation("async")) {
                continue;
            }
            for (final Type.DeclaredType supertype : declaredSupertypes(type)) {
                for (final MethodDefinition inherited : model.definition(supertype).methods()) {
                    if (inherited.name().equals(method.name()) && inherited.hasAnnotation("async")
                            && sameParameters(method, inherited, supertype, model)) {
                        final Type expected = model.substitute(supertype, inherited.returnType());
                        if (!expected.text().equals(method.returnType().text())) {
                            return Optional.of("overrides the @@async method " + supertype.name() + "."
                                    + method.name() + " with the return type " + method.returnType().text()
                                    + " instead of " + expected.text() + "; CompletionStage<T> is invariant in Java");
                        }
                    }
                }
            }
        }
        return Optional.empty();
    }

    private static boolean sameParameters(final MethodDefinition method, final MethodDefinition inherited,
                                          final Type.DeclaredType supertype, final LinkedModel model) {
        if (method.parameters().size() != inherited.parameters().size()) {
            return false;
        }
        for (int i = 0; i < method.parameters().size(); i++) {
            if (!model.substitute(supertype, inherited.parameters().get(i).type()).text()
                    .equals(method.parameters().get(i).type().text())) {
                return false;
            }
        }
        return true;
    }

    private static String kind(final JavaContext context, final QualifiedName name) {
        return context.model().type(name).map(type -> switch (type) {
            case TypeDefinition.EnumDefinition ignored -> "enum";
            case TypeDefinition.ComplexTypeDefinition complex when complex.abstraction() ->
                    context.isClass(name) ? "abstract class" : "interface";
            case TypeDefinition.ComplexTypeDefinition ignored -> context.isClass(name) ? "class" : "record";
        }).orElse("unknown");
    }

    private static Optional<String> unsupported(final TypeDefinition type, final JavaContext context) {
        try {
            generate("plan", type, context);
            return Optional.empty();
        } catch (final JavaTypes.UnsupportedTypeException e) {
            return Optional.of(e.getMessage());
        }
    }

    private static void referencedTypes(final @Nullable Type type, final Set<QualifiedName> names) {
        switch (type) {
            case null -> {
            }
            case Type.DeclaredType declared -> {
                names.add(declared.name());
                declared.arguments().forEach(a -> referencedTypes(a, names));
            }
            case Type.BasicType basic -> basic.arguments().forEach(a -> referencedTypes(a, names));
            case Type.WildcardType wildcard -> referencedTypes(wildcard.upperBound(), names);
            case Type.FunctionType function -> {
                referencedTypes(function.returnType(), names);
                function.parameters().forEach(p -> referencedTypes(p.type(), names));
            }
            default -> {
            }
        }
    }

    private static List<Module> modules(final LinkedModel model) {
        final List<String> problems = new ArrayList<>();
        final Map<String, String> folderOf = new TreeMap<>();
        final SortedMap<String, List<NamespaceDefinition>> namespacesByFolder = new TreeMap<>();
        for (final NamespaceDefinition namespace : model.namespaces()) {
            final SortedSet<String> folders = new TreeSet<>();
            for (final NamespaceDefinition.Source source : namespace.sources()) {
                final int slash = source.file().indexOf('/');
                if (slash < 0) {
                    problems.add("Spec file '" + source.file() + "' of namespace '" + namespace.name()
                            + "' is not inside a folder; the folder defines the Java module");
                } else {
                    folders.add(source.file().substring(0, slash));
                }
            }
            if (folders.size() > 1) {
                problems.add("Namespace '" + namespace.name() + "' is spread over the spec folders " + folders
                        + "; a Java package must belong to exactly one module");
            }
            if (!folders.isEmpty()) {
                folderOf.put(namespace.name(), folders.first());
                namespacesByFolder.computeIfAbsent(folders.first(), k -> new ArrayList<>()).add(namespace);
            }
        }
        final List<Module> modules = new ArrayList<>();
        namespacesByFolder.forEach((folder, namespaces) -> {
            final SortedSet<String> requires = new TreeSet<>();
            for (final NamespaceDefinition namespace : namespaces) {
                for (final String required : namespace.requiredNamespaces()) {
                    final String requiredFolder = folderOf.get(required);
                    if (requiredFolder != null && !requiredFolder.equals(folder)) {
                        requires.add(JavaNames.moduleName(requiredFolder));
                    }
                }
            }
            modules.add(new Module(JavaNames.moduleName(folder), folder, List.copyOf(namespaces), requires));
        });
        findCycle(modules).ifPresent(cycle -> problems.add("Dependency cycle between Java modules: " + cycle));
        if (!problems.isEmpty()) {
            throw new GenerationException(problems);
        }
        return modules;
    }

    private static Optional<String> findCycle(final List<Module> modules) {
        final Map<String, SortedSet<String>> edges = new TreeMap<>();
        modules.forEach(m -> edges.put(m.name(), m.requires()));
        final Set<String> done = new HashSet<>();
        for (final String start : edges.keySet()) {
            final Optional<String> cycle = visit(start, edges, new ArrayList<>(), done);
            if (cycle.isPresent()) {
                return cycle;
            }
        }
        return Optional.empty();
    }

    private static Optional<String> visit(final String module, final Map<String, SortedSet<String>> edges,
                                                    final List<String> path, final Set<String> done) {
        final int index = path.indexOf(module);
        if (index >= 0) {
            final List<String> cycle = new ArrayList<>(path.subList(index, path.size()));
            cycle.add(module);
            return Optional.of(String.join(" -> ", cycle));
        }
        if (!done.add(module)) {
            return Optional.empty();
        }
        path.add(module);
        for (final String next : edges.getOrDefault(module, new TreeSet<>())) {
            final Optional<String> cycle = visit(next, edges, path, done);
            if (cycle.isPresent()) {
                return cycle;
            }
        }
        path.removeLast();
        return Optional.empty();
    }

    private static GeneratedFile moduleInfo(final Module module, final Set<String> packagesWithTypes,
                                            final List<String> sdkPackages) {
        final StringBuilder java = new StringBuilder(HEADER).append('\n');
        java.append("import org.jspecify.annotations.NullMarked;\n\n");
        java.append(MarkdownComment.render("", List.of(
                "Module `" + module.name() + "` of the Hiero SDK.",
                "Packages:\n" + String.join("\n", Stream.concat(module.namespaces().stream()
                        .map(n -> JavaNames.packageName(n.name())), sdkPackages.stream())
                        .map(p -> "- `" + p + "`")
                        .toList()))));
        // non-null by default in all packages, like the meta-language; only @@nullable needs @Nullable
        java.append("@NullMarked\n");
        java.append("module ").append(module.name()).append(" {\n");
        for (final String required : module.requires()) {
            // transitive: specs only contain public API, so every type of a required module is part of it
            java.append("    requires transitive ").append(required).append(";\n");
        }
        // static: only needed at compile time; transitive: the annotations are part of the exported API
        java.append("    requires static transitive ").append(JSPECIFY_MODULE).append(";\n");
        java.append('\n');
        for (final NamespaceDefinition namespace : module.namespaces()) {
            if (packagesWithTypes.contains(namespace.name())) {
                java.append("    exports ").append(JavaNames.packageName(namespace.name())).append(";\n");
            } else {
                // the module system rejects exporting a package that contains no types (package-info.java alone
                // does not count), so the export is enabled as soon as types are generated for the package
                java.append("    // exports ").append(JavaNames.packageName(namespace.name()))
                        .append("; (enabled as soon as the package contains generated types)\n");
            }
        }
        // packages of the SDK itself, e.g. the @ThreadSafe annotation
        sdkPackages.forEach(p -> java.append("    exports ").append(p).append(";\n"));
        java.append("}\n");
        return new GeneratedFile(JavaNames.sourceRoot(module.name()) + "/module-info.java", java.toString());
    }

    /**
     * The package documentation is the user-facing description of the namespace: the {@code ## Description} of its
     * spec file(s). Without a description no {@code package-info.java} is generated.
     */
    private static Optional<GeneratedFile> packageInfo(final Module module,
                                                                 final NamespaceDefinition namespace) {
        final List<String> paragraphs = namespace.sources().stream()
                .map(NamespaceDefinition.Source::description)
                .filter(d -> !d.isBlank())
                .toList();
        if (paragraphs.isEmpty()) {
            return Optional.empty();
        }
        final String java = HEADER + '\n'
                + MarkdownComment.render("", paragraphs)
                + "package " + JavaNames.packageName(namespace.name()) + ";\n";
        return Optional.of(new GeneratedFile(
                JavaNames.packageDirectory(module.name(), namespace.name()) + "/package-info.java", java));
    }
}
