package org.hiero.sdk.v3.metalang.generator.java;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.SortedMap;
import java.util.SortedSet;
import java.util.TreeMap;
import java.util.TreeSet;
import org.hiero.sdk.v3.metalang.generator.GeneratedFile;
import org.hiero.sdk.v3.metalang.generator.GenerationException;
import org.hiero.sdk.v3.metalang.model.LinkedModel;
import org.hiero.sdk.v3.metalang.model.NamespaceDefinition;
import org.hiero.sdk.v3.metalang.model.TypeDefinition;

/**
 * Generates the Java API from a {@link LinkedModel}.
 *
 * <p>Layout: one JPMS module per spec folder ({@link JavaNames#moduleName(String)}), containing one package per
 * namespace of that folder. Generated so far: the {@code module-info.java} of every module, the
 * {@code package-info.java} of every package and every enum ({@link EnumGenerator}). Documentation is written as Markdown documentation comments
 * ({@code ///}, Java 23+); the SDK targets Java 25.
 *
 * <p>The output is deterministic: the same model always produces byte-identical files in the same order.
 */
public final class JavaGenerator {

    /** First line of every generated file. */
    static final String HEADER = "// Generated by metalang from the Hiero SDK V3 specs. Do not edit.\n";

    /** The JPMS module of the nullness annotations used by the Java mapping. */
    static final String JSPECIFY_MODULE = "org.jspecify";

    /** A module: its spec folder, its namespaces and the modules it requires. */
    private record Module(String name, String folder, List<NamespaceDefinition> namespaces, SortedSet<String> requires) {
    }

    /**
     * Generates all files for the given model.
     *
     * @param model the linked model (must be free of validation errors)
     * @return the generated files, sorted by path
     * @throws GenerationException if the model cannot be mapped to Java modules (namespace spread over several
     *                             spec folders, spec file outside of a folder, dependency cycle between modules)
     */
    public List<GeneratedFile> generate(final LinkedModel model) {
        Objects.requireNonNull(model, "model must not be null");
        final List<GeneratedFile> files = new ArrayList<>();
        final List<String> problems = new ArrayList<>();
        for (final Module module : modules(model)) {
            final Set<String> packagesWithTypes = new TreeSet<>();
            for (final NamespaceDefinition namespace : module.namespaces()) {
                packageInfo(module, namespace).ifPresent(files::add);
                for (final TypeDefinition type : model.types(namespace.name())) {
                    if (type instanceof TypeDefinition.EnumDefinition enumType) {
                        try {
                            files.add(EnumGenerator.generate(module.name(), enumType));
                            packagesWithTypes.add(namespace.name());
                        } catch (final JavaTypes.UnsupportedTypeException e) {
                            problems.add(enumType.name() + ": " + e.getMessage());
                        }
                    }
                }
            }
            files.add(moduleInfo(module, packagesWithTypes));
        }
        if (!problems.isEmpty()) {
            throw new GenerationException(problems);
        }
        return files.stream().sorted().toList();
    }

    private static List<Module> modules(final LinkedModel model) {
        final List<String> problems = new ArrayList<>();
        final Map<String, String> folderOf = new TreeMap<>();
        final SortedMap<String, List<NamespaceDefinition>> namespacesByFolder = new TreeMap<>();
        for (final NamespaceDefinition namespace : model.namespaces()) {
            final SortedSet<String> folders = new TreeSet<>();
            for (final NamespaceDefinition.Source source : namespace.sources()) {
                final int slash = source.file().indexOf('/');
                if (slash < 0) {
                    problems.add("Spec file '" + source.file() + "' of namespace '" + namespace.name()
                            + "' is not inside a folder; the folder defines the Java module");
                } else {
                    folders.add(source.file().substring(0, slash));
                }
            }
            if (folders.size() > 1) {
                problems.add("Namespace '" + namespace.name() + "' is spread over the spec folders " + folders
                        + "; a Java package must belong to exactly one module");
            }
            if (!folders.isEmpty()) {
                folderOf.put(namespace.name(), folders.first());
                namespacesByFolder.computeIfAbsent(folders.first(), k -> new ArrayList<>()).add(namespace);
            }
        }
        final List<Module> modules = new ArrayList<>();
        namespacesByFolder.forEach((folder, namespaces) -> {
            final SortedSet<String> requires = new TreeSet<>();
            for (final NamespaceDefinition namespace : namespaces) {
                for (final String required : namespace.requiredNamespaces()) {
                    final String requiredFolder = folderOf.get(required);
                    if (requiredFolder != null && !requiredFolder.equals(folder)) {
                        requires.add(JavaNames.moduleName(requiredFolder));
                    }
                }
            }
            modules.add(new Module(JavaNames.moduleName(folder), folder, List.copyOf(namespaces), requires));
        });
        findCycle(modules).ifPresent(cycle -> problems.add("Dependency cycle between Java modules: " + cycle));
        if (!problems.isEmpty()) {
            throw new GenerationException(problems);
        }
        return modules;
    }

    private static Optional<String> findCycle(final List<Module> modules) {
        final Map<String, SortedSet<String>> edges = new TreeMap<>();
        modules.forEach(m -> edges.put(m.name(), m.requires()));
        final Set<String> done = new HashSet<>();
        for (final String start : edges.keySet()) {
            final Optional<String> cycle = visit(start, edges, new ArrayList<>(), done);
            if (cycle.isPresent()) {
                return cycle;
            }
        }
        return Optional.empty();
    }

    private static Optional<String> visit(final String module, final Map<String, SortedSet<String>> edges,
                                                    final List<String> path, final Set<String> done) {
        final int index = path.indexOf(module);
        if (index >= 0) {
            final List<String> cycle = new ArrayList<>(path.subList(index, path.size()));
            cycle.add(module);
            return Optional.of(String.join(" -> ", cycle));
        }
        if (!done.add(module)) {
            return Optional.empty();
        }
        path.add(module);
        for (final String next : edges.getOrDefault(module, new TreeSet<>())) {
            final Optional<String> cycle = visit(next, edges, path, done);
            if (cycle.isPresent()) {
                return cycle;
            }
        }
        path.removeLast();
        return Optional.empty();
    }

    private static GeneratedFile moduleInfo(final Module module, final Set<String> packagesWithTypes) {
        final StringBuilder java = new StringBuilder(HEADER).append('\n');
        java.append(MarkdownComment.render("", List.of(
                "Module `" + module.name() + "` of the Hiero SDK.",
                "Packages:\n" + String.join("\n", module.namespaces().stream()
                        .map(n -> "- `" + JavaNames.packageName(n.name()) + "`")
                        .toList()))));
        java.append("module ").append(module.name()).append(" {\n");
        for (final String required : module.requires()) {
            // transitive: specs only contain public API, so every type of a required module is part of it
            java.append("    requires transitive ").append(required).append(";\n");
        }
        // static: only needed at compile time; transitive: the annotations are part of the exported API
        java.append("    requires static transitive ").append(JSPECIFY_MODULE).append(";\n");
        java.append('\n');
        for (final NamespaceDefinition namespace : module.namespaces()) {
            if (packagesWithTypes.contains(namespace.name())) {
                java.append("    exports ").append(JavaNames.packageName(namespace.name())).append(";\n");
            } else {
                // the module system rejects exporting a package that contains no types (package-info.java alone
                // does not count), so the export is enabled as soon as types are generated for the package
                java.append("    // exports ").append(JavaNames.packageName(namespace.name()))
                        .append("; (enabled as soon as the package contains generated types)\n");
            }
        }
        java.append("}\n");
        return new GeneratedFile(JavaNames.sourceRoot(module.name()) + "/module-info.java", java.toString());
    }

    /**
     * The package documentation is the user-facing description of the namespace: the {@code ## Description} of its
     * spec file(s). Without a description no {@code package-info.java} is generated.
     */
    private static Optional<GeneratedFile> packageInfo(final Module module,
                                                                 final NamespaceDefinition namespace) {
        final List<String> paragraphs = namespace.sources().stream()
                .map(NamespaceDefinition.Source::description)
                .filter(d -> !d.isBlank())
                .toList();
        if (paragraphs.isEmpty()) {
            return Optional.empty();
        }
        final String java = HEADER + '\n'
                + MarkdownComment.render("", paragraphs)
                + "package " + JavaNames.packageName(namespace.name()) + ";\n";
        return Optional.of(new GeneratedFile(
                JavaNames.packageDirectory(module.name(), namespace.name()) + "/package-info.java", java));
    }
}
