package org.hiero.sdk.v3.metalang.generator.java;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import org.hiero.sdk.v3.metalang.MetaLang;
import org.hiero.sdk.v3.metalang.TestSpecs;
import org.hiero.sdk.v3.metalang.generator.GeneratedFile;
import org.hiero.sdk.v3.metalang.model.LinkedModel;
import org.hiero.sdk.v3.metalang.model.QualifiedName;
import org.hiero.sdk.v3.metalang.model.TypeDefinition;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

class InterfaceGeneratorTest {

    @TempDir
    Path temp;

    private static LinkedModel model(final Map<String, String> schemas) {
        final Map<String, String> documents = new java.util.TreeMap<>();
        schemas.forEach((file, schema) -> documents.put(file, TestSpecs.markdown(schema)));
        return LinkedModel.of(new MetaLang().validate(documents).model());
    }

    private static LinkedModel model(final String schema) {
        return model(Map.of("f/a.md", schema));
    }

    /**
     * A configuration that makes every abstraction an interface (abstractions with attributes would otherwise become
     * abstract classes; those are tested in {@code ClassGeneratorTest}). Abstractions with a {@code @@finalMethod}
     * cannot be interfaces.
     */
    private static JavaGeneratorConfig allInterfaces(final LinkedModel model) {
        return new JavaGeneratorConfig(model.types().stream()
                .filter(t -> t instanceof TypeDefinition.ComplexTypeDefinition c && c.abstraction())
                .filter(t -> t.methods().stream().noneMatch(m -> m.hasAnnotation("finalMethod")))
                .map(TypeDefinition::name).collect(Collectors.toSet()));
    }

    private static JavaGenerator generator(final LinkedModel model) {
        return new JavaGenerator(allInterfaces(model));
    }

    private static String source(final List<GeneratedFile> files, final String type) {
        return files.stream().filter(f -> f.path().endsWith("/" + type + ".java")).findFirst().orElseThrow()
                .content();
    }

    /** Generates the schema, compiles the result with -Xlint:all -Werror and returns the files. */
    private List<GeneratedFile> compiled(final String schema) throws IOException {
        final LinkedModel model = model(schema);
        final List<GeneratedFile> files = generator(model).generate(model);
        final GeneratedJava.Compilation compilation = GeneratedJava.compile(files, temp);
        assertThat(compilation.diagnostics()).isEmpty();
        assertThat(compilation.success()).isTrue();
        return files;
    }

    @Nested
    class Members {

        @Test
        void shouldGenerateAbstractAccessorsSettersAndMethods() throws IOException {
            // WHEN
            final List<GeneratedFile> files = compiled("""
                    namespace a
                    // A named thing.
                    abstraction Named {
                        @@immutable name: string        // the name
                        @@nullable @@deprecated note: string
                        // Greets someone.
                        @@throws(not-found-error) string greet(@@nullable to: string, more: string...)
                        @@async void refresh()
                        @@static Named of(name: string)
                    }
                    """);

            // THEN
            assertThat(source(files, "Named")).isEqualTo("""
                    // Generated by metalang from the Hiero SDK V3 specs. Do not edit.

                    package org.hiero.a;

                    import java.util.NoSuchElementException;
                    import java.util.concurrent.CompletionStage;
                    import org.jspecify.annotations.Nullable;

                    /// A named thing.
                    public interface Named {

                        /// the name
                        String name();

                        /// Returns the `note`.
                        ///
                        /// @deprecated Retained for compatibility; do not use it in new code.
                        @Deprecated
                        @Nullable String note();

                        /// Sets the `note`.
                        ///
                        /// @param note the new value
                        /// @return this object
                        /// @deprecated Retained for compatibility; do not use it in new code.
                        @Deprecated
                        Named setNote(final @Nullable String note);

                        /// Greets someone.
                        ///
                        /// @throws NoSuchElementException if a not found error occurs
                        String greet(final @Nullable String to, final String... more);

                        CompletionStage<Void> refresh();

                        static Named of(final String name) {
                            throw new UnsupportedOperationException("Not implemented yet: Named.of");
                        }
                    }
                    """);
        }

        @Test
        void shouldReturnTheSelfTypeFromSettersAndRenameShadowingTypeVariables() throws IOException {
            // WHEN
            final List<GeneratedFile> files = compiled("""
                    namespace a
                    abstraction Receipt { }
                    abstraction Builder<$$Receipt extends Receipt, $$Self extends Builder<$$Receipt, $$Self>> {
                        memo: string
                        $$Receipt build()
                    }
                    abstraction Plain<$$T> {
                        value: $$T
                    }
                    """);

            // THEN
            assertThat(source(files, "Builder"))
                    .contains("public interface Builder<ReceiptT extends Receipt, Self extends Builder<ReceiptT, Self>> {")
                    .contains("Self setMemo(final String memo);")
                    .contains("ReceiptT build();");
            assertThat(source(files, "Plain")).contains("Plain<T> setValue(final T value);");
        }
    }

    @Nested
    class Implementations {

        @Test
        void shouldImplementGenericInterfacesWithBoxedTypesAndOverrideAnnotations() throws IOException {
            // WHEN a record and an enum implement interfaces whose members use type variables
            final List<GeneratedFile> files = compiled("""
                    namespace a
                    abstraction Holder<$$T> {
                        @@immutable value: $$T
                        $$T get(fallback: $$T)
                        void put(value: $$T)
                    }
                    abstraction Coded { @@immutable code: int32 }
                    abstraction Sized extends Holder<int64> { @@immutable size: int32 }
                    LongHolder extends Sized { }
                    enum Status(code: int32) extends Coded {
                        OK(0)
                        int32 next()
                    }
                    """);

            // THEN
            assertThat(source(files, "Sized")).contains("public interface Sized extends Holder<Long> {");
            assertThat(source(files, "LongHolder"))
                    .contains("public record LongHolder(Long value, int size) implements Sized {")
                    .contains("    @Override\n    public Long get(final Long fallback) {")
                    .contains("    @Override\n    public void put(final Long value) {");
            assertThat(source(files, "Status"))
                    .contains("public enum Status implements Coded {")
                    .contains("    @Override\n    public int code() {")
                    .contains("    public int next() {");
        }

        @Test
        void shouldKeepTheBoxedTypeWhenNullabilityIsNarrowed() throws IOException {
            assertThat(source(compiled("""
                    namespace a
                    abstraction Identifier { @@immutable @@nullable num: uint32 }
                    abstraction Strict extends Identifier { @@immutable @@override num: uint32 }
                    Numeric extends Strict { }
                    """), "Strict")).contains("    @Override\n    Long num();");
        }

        @Test
        void shouldUseSealedAndNonSealedInterfaces() throws IOException {
            // WHEN
            final List<GeneratedFile> files = compiled("""
                    namespace a
                    @@sealed(Circle, Polygon)
                    abstraction Shape { }
                    Circle extends Shape { @@immutable radius: int32 }
                    abstraction Polygon extends Shape { @@immutable corners: int32 }
                    Square extends Polygon { @@immutable corners: int32 }
                    """);

            // THEN
            assertThat(source(files, "Shape")).contains("public sealed interface Shape permits Circle, Polygon {");
            assertThat(source(files, "Polygon")).contains("public non-sealed interface Polygon extends Shape {");
            assertThat(source(files, "Circle")).contains("public record Circle(int radius) implements Shape {");
        }

        @Test
        void shouldWriteSupertypesThatAreNotGeneratedAsComment() {
            // WHEN a record implements an interface that is deferred (it extends a class)
            final LinkedModel model = model("""
                    namespace a
                    Base { @@immutable a: int32 }
                    abstraction Waiting extends Base { }
                    abstraction Ready { }
                    Both extends Waiting, Ready { @@immutable x: int32 }
                    """);
            final List<GeneratedFile> files = generator(model).generate(model);

            // THEN
            assertThat(source(files, "Both")).contains("public record Both(int a, int x) implements Ready"
                    + " /* implements org.hiero.a.Waiting (enabled as soon as it is generated) */ {");
        }
    }

    @Nested
    class Deferral {

        @Test
        void shouldDeferInterfacesThatCannotBeGeneratedYet() {
            // GIVEN
            final LinkedModel model = model(Map.of("one/a.md", """
                    namespace a
                    Mutable { value: int32
                        void run(cb: streamResult<int8>) }
                    abstraction Uses { @@immutable m: Mutable }
                    abstraction Child extends Uses { }
                    Base { @@immutable a: int32 }
                    Derived extends Base { @@immutable b: int32 }
                    abstraction OnClass extends Base { }
                    @@sealed(Open, b.Remote)
                    abstraction Closed { }
                    Open extends Closed { value: int32
                        void run(cb: streamResult<int8>) }
                    @@sealed(Fine)
                    abstraction AlsoClosed { }
                    Fine extends AlsoClosed { @@immutable a: int32 }
                    abstraction Final { @@finalMethod int32 id() }
                    abstraction AfterFinal extends Final { }
                    """, "two/b.md", """
                    namespace b
                    requires {Closed} from a
                    Remote extends Closed { @@immutable a: int32 }
                    """));

            // WHEN
            final Map<QualifiedName, String> deferred = generator(model).deferredTypes(model);

            // THEN
            final String noMapping = "Type 'streamResult<int8>' has no Java mapping yet";
            assertThat(deferred).containsExactly(
                    Map.entry(new QualifiedName("a", "Child"), "refers to a.Mutable (class, not generated yet)"),
                    Map.entry(new QualifiedName("a", "Closed"), "permits b.Remote, which is in another Java module"),
                    Map.entry(new QualifiedName("a", "Mutable"), noMapping),
                    Map.entry(new QualifiedName("a", "OnClass"), "an interface cannot extend the class a.Base"),
                    Map.entry(new QualifiedName("a", "Open"), noMapping),
                    Map.entry(new QualifiedName("a", "Uses"), "refers to a.Mutable (class, not generated yet)"));
            final LinkedModel remote = model(Map.of("one/a.md", """
                    namespace a
                    @@sealed(b.Remote)
                    abstraction Closed { }
                    """, "two/b.md", """
                    namespace b
                    requires {Closed} from a
                    Remote extends Closed { @@immutable a: int32 }
                    """));
            assertThat(generator(remote).deferredTypes(remote)).containsEntry(new QualifiedName("a", "Closed"),
                    "permits b.Remote, which is in another Java module");
            // a permitted subtype that is not generated
            final LinkedModel open = model("""
                    namespace a
                    @@sealed(Open)
                    abstraction Closed { }
                    Open extends Closed { value: int32
                        void run(cb: streamResult<int8>) }
                    """);
            assertThat(generator(open).deferredTypes(open)).containsEntry(new QualifiedName("a", "Closed"),
                    "permits a.Open (class, not generated yet)");
        }

        @Test
        void shouldNameAbstractClassesInReasons() {
            assertThat(new JavaGenerator().deferredTypes(model("""
                    namespace a
                    abstraction Final { @@finalMethod int32 id()
                        void run(cb: streamResult<int8>) }
                    UsesFinal { @@immutable f: Final }
                    """))).containsEntry(new QualifiedName("a", "UsesFinal"),
                    "refers to a.Final (abstract class, not generated yet)");
        }
    }
}
