package org.hiero.sdk.v3.metalang.generator.ts;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.SortedMap;
import org.hiero.sdk.v3.metalang.generator.GeneratedFile;
import org.hiero.sdk.v3.metalang.generator.SpecFolders;
import org.hiero.sdk.v3.metalang.model.LinkedModel;
import org.hiero.sdk.v3.metalang.model.NamespaceDefinition;
import org.hiero.sdk.v3.metalang.model.QualifiedName;
import org.hiero.sdk.v3.metalang.model.TypeDefinition;

/**
 * Generates the TypeScript API from a {@link LinkedModel}: an npm workspace with one package per spec folder
 * ({@link TsProjectGenerator}), one directory per namespace with one file per type ({@link TsTypeGenerator}), the
 * functions, constants and error classes of the namespace and an {@code index.ts} that the package exports as subpath
 * ({@link TsNamespaceGenerator}) and the tests ({@link TsTestGenerator}). The types the API uses besides the specs
 * ({@code Duration}, {@code StreamItem}, ...) are not generated: they are the hand-written support package
 * ({@code sdk-ts/support}), a dependency of the packages that use them. See {@code guidelines/api-best-practices-ts.md} for the mapping. The output is
 * deterministic.
 */
public final class TsGenerator {

    /** Text in the first line of every generated file; it marks the files the generator may replace or delete. */
    public static final String MARKER = "Generated by metalang from the Hiero SDK V3 specs. Do not edit.";

    /** First line of every generated TypeScript file. */
    static final String HEADER = "// " + MARKER + "\n";

    private final TsGeneratorConfig config;

    /** Creates a generator with the default configuration. */
    public TsGenerator() {
        this(TsGeneratorConfig.DEFAULT);
    }

    /**
     * Creates a generator.
     *
     * @param config the project-specific configuration
     */
    public TsGenerator(final TsGeneratorConfig config) {
        this.config = Objects.requireNonNull(config, "config must not be null");
    }

    /**
     * Generates all files.
     *
     * @param model the linked model
     * @return the files, sorted by path
     * @throws org.hiero.sdk.v3.metalang.generator.GenerationException if the specs cannot be mapped to packages
     */
    public List<GeneratedFile> generate(final LinkedModel model) {
        Objects.requireNonNull(model, "model must not be null");
        final TsContext context = new TsContext(config, model);
        final List<GeneratedFile> files = new ArrayList<>();
        final String supportImport = "from \"" + TsNames.supportPackage(config) + "\"";
        boolean anySupport = false;
        for (final SpecFolders.Folder folder : context.folders()) {
            final List<GeneratedFile> folderFiles = new ArrayList<>();
            final List<String> subpaths = new ArrayList<>();
            for (final NamespaceDefinition namespace : folder.namespaces()) {
                final List<GeneratedFile> namespaceFiles = new ArrayList<>();
                final List<TypeDefinition> types = model.types(namespace.name());
                for (final TypeDefinition type : types) {
                    if (context.isGenerated(type.name())) {
                        namespaceFiles.add(TsTypeGenerator.generate(type, context));
                        TsTestGenerator.generate(type, context).ifPresent(namespaceFiles::add);
                    }
                }
                TsNamespaceGenerator.functions(namespace.name(), context).ifPresent(f -> {
                    namespaceFiles.add(f);
                    TsTestGenerator.functions(namespace.name(), context).ifPresent(namespaceFiles::add);
                });
                TsNamespaceGenerator.constants(namespace.name(), context).ifPresent(namespaceFiles::add);
                TsNamespaceGenerator.errors(namespace.name(), context).ifPresent(namespaceFiles::add);
                namespaceFiles.add(TsNamespaceGenerator.index(namespace, TsNamespaceGenerator.modules(namespace.name(),
                        types, namespaceFiles, context), context));
                folderFiles.addAll(namespaceFiles);
                subpaths.add(TsNames.namespacePath(namespace.name()));
            }
            // the hand-written support package is a dependency of every package whose code imports from it
            final boolean support = folderFiles.stream().anyMatch(f -> f.content().contains(supportImport));
            anySupport |= support;
            files.addAll(folderFiles);
            files.addAll(TsProjectGenerator.folder(folder, subpaths, config, support));
        }
        files.addAll(TsProjectGenerator.root(context.folders(), config, anySupport));
        return files.stream().sorted().toList();
    }

    /**
     * Returns the declarations that are not generated yet, with the reason.
     *
     * @param model the linked model
     * @return the deferred declarations, sorted by name
     */
    public SortedMap<QualifiedName, String> deferredTypes(final LinkedModel model) {
        return new TsContext(config, model).deferred();
    }
}
