package org.hiero.sdk.v3.metalang.generator.ts;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.SortedMap;
import org.hiero.sdk.v3.metalang.generator.GeneratedFile;
import org.hiero.sdk.v3.metalang.generator.SpecFolders;
import org.hiero.sdk.v3.metalang.model.LinkedModel;
import org.hiero.sdk.v3.metalang.model.NamespaceDefinition;
import org.hiero.sdk.v3.metalang.model.QualifiedName;
import org.hiero.sdk.v3.metalang.model.TypeDefinition;

/**
 * Generates the TypeScript API from a {@link LinkedModel}: an npm workspace with one package per spec folder
 * ({@link TsProjectGenerator}), one directory per namespace with one file per type ({@link TsTypeGenerator}), the
 * functions, constants and error classes of the namespace and an {@code index.ts} that the package exports as subpath
 * ({@link TsNamespaceGenerator}), the support files of the TypeScript guideline ({@code guidelines/ts-files}) and the
 * tests ({@link TsTestGenerator}). See {@code guidelines/api-best-practices-ts.md} for the mapping. The output is
 * deterministic.
 */
public final class TsGenerator {

    /** Text in the first line of every generated file; it marks the files the generator may replace or delete. */
    public static final String MARKER = "Generated by metalang from the Hiero SDK V3 specs. Do not edit.";

    /** First line of every generated TypeScript file. */
    static final String HEADER = "// " + MARKER + "\n";

    private final TsGeneratorConfig config;

    /** Creates a generator with the default configuration. */
    public TsGenerator() {
        this(TsGeneratorConfig.DEFAULT);
    }

    /**
     * Creates a generator.
     *
     * @param config the project-specific configuration
     */
    public TsGenerator(final TsGeneratorConfig config) {
        this.config = Objects.requireNonNull(config, "config must not be null");
    }

    /**
     * Generates all files.
     *
     * @param model the linked model
     * @return the files, sorted by path
     * @throws org.hiero.sdk.v3.metalang.generator.GenerationException if the specs cannot be mapped to packages
     */
    public List<GeneratedFile> generate(final LinkedModel model) {
        Objects.requireNonNull(model, "model must not be null");
        final TsContext context = new TsContext(config, model);
        final List<GeneratedFile> files = new ArrayList<>();
        for (final SpecFolders.Folder folder : context.folders()) {
            final List<String> subpaths = new ArrayList<>();
            for (final NamespaceDefinition namespace : folder.namespaces()) {
                final List<GeneratedFile> namespaceFiles = new ArrayList<>();
                final List<TypeDefinition> types = model.types(namespace.name());
                for (final TypeDefinition type : types) {
                    if (context.isGenerated(type.name())) {
                        namespaceFiles.add(TsTypeGenerator.generate(type, context));
                        TsTestGenerator.generate(type, context).ifPresent(namespaceFiles::add);
                    }
                }
                TsNamespaceGenerator.functions(namespace.name(), context).ifPresent(f -> {
                    namespaceFiles.add(f);
                    TsTestGenerator.functions(namespace.name(), context).ifPresent(namespaceFiles::add);
                });
                TsNamespaceGenerator.constants(namespace.name(), context).ifPresent(namespaceFiles::add);
                TsNamespaceGenerator.errors(namespace.name(), context).ifPresent(namespaceFiles::add);
                namespaceFiles.add(TsNamespaceGenerator.index(namespace, TsNamespaceGenerator.modules(namespace.name(),
                        types, namespaceFiles, context), context));
                files.addAll(namespaceFiles);
                subpaths.add(TsNames.namespacePath(namespace.name()));
            }
            if (folder.name().equals(supportFolder(context)) && !context.support().isEmpty()) {
                files.addAll(support(folder.name(), context));
                subpaths.add(TsNames.SUPPORT);
            }
            files.addAll(TsProjectGenerator.folder(folder, subpaths, config));
        }
        files.addAll(TsProjectGenerator.root(context.folders(), config));
        return files.stream().sorted().toList();
    }

    /**
     * Returns the declarations that are not generated yet, with the reason.
     *
     * @param model the linked model
     * @return the deferred declarations, sorted by name
     */
    public SortedMap<QualifiedName, String> deferredTypes(final LinkedModel model) {
        return new TsContext(config, model).deferred();
    }

    private static String supportFolder(final TsContext context) {
        try {
            return context.supportFolder();
        } catch (final NullPointerException e) {
            return "";
        }
    }

    private static List<GeneratedFile> support(final String folder, final TsContext context) {
        final String directory = TsNames.packageDirectory(folder) + "/src/" + TsNames.SUPPORT;
        final List<GeneratedFile> files = new ArrayList<>();
        final StringBuilder index = new StringBuilder(HEADER).append('\n')
                .append(TsDoc.render("", List.of("Types that the generated API uses besides the types of the specs."),
                        List.of("@packageDocumentation"), false));
        for (final String name : context.support()) {
            files.add(new GeneratedFile(directory + "/" + name + ".ts", HEADER + "\n" + source(name)));
            index.append("export * from \"./").append(name).append(".js\";\n");
        }
        files.add(new GeneratedFile(directory + "/index.ts", index.toString()));
        return files;
    }

    /**
     * Returns a support file as it is in the guideline ({@code guidelines/ts-files}).
     *
     * @param name the file name without extension
     * @return the source
     */
    static String source(final String name) {
        try (InputStream in = TsGenerator.class.getResourceAsStream("support/" + name + ".ts")) {
            if (in == null) {
                throw new IllegalStateException("Support file " + name + ".ts is missing; it is copied from "
                        + "guidelines/ts-files by the build");
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (final IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
