// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop.money;

import static org.junit.jupiter.api.Assertions.*;

import java.math.BigInteger;
import java.time.Duration;
import java.util.Arrays;
import java.util.List;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Plan`, generated from the specs.
@DisplayName("Plan")
class PlanTest {

    @Test
    @DisplayName("the constants have the attribute values of the specs")
    void shouldProvideTheAttributesOfTheConstants() {
        assertValue(Duration.ofSeconds(30L), Plan.BASIC.timeout());
        assertValue(new BigInteger("1000"), Plan.BASIC.limit());
        assertValue(List.of("a", "b"), Plan.BASIC.tags());
        assertValue(Duration.ofSeconds(3_600L), Plan.PREMIUM.timeout());
        assertValue(new BigInteger("100000000000000000000"), Plan.PREMIUM.limit());
        assertValue(List.of(), Plan.PREMIUM.tags());
    }

    /// Asserts that two values are equal; arrays by their content.
    private static void assertValue(final @Nullable Object expected, final @Nullable Object actual) {
        if (expected instanceof byte[] bytes && actual instanceof byte[] other) {
            assertArrayEquals(bytes, other, () -> "expected " + Arrays.toString(bytes) + " but was " + Arrays.toString(other));
        } else {
            assertEquals(expected, actual);
        }
    }
}
