// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Base`, generated from the specs.
@DisplayName("Base")
class BaseTest {

    @Test
    @DisplayName("creates a Base and returns the values")
    void shouldCreateAndReturnTheValues() {
        final int a = aValue();
        final Base subject = new Base(a);
        assertValue(a, subject.a());
    }

    @Test
    @DisplayName("a: accepts the minimum (-2147483648)")
    void shouldAcceptAAtMinimum() {
        final int value = Integer.MIN_VALUE;
        final Base subject = new Base(value);
        assertValue(value, subject.a());
    }

    @Test
    @DisplayName("a: accepts the maximum (2147483647)")
    void shouldAcceptAAtMaximum() {
        final int value = 2147483647;
        final Base subject = new Base(value);
        assertValue(value, subject.a());
    }

    @Test
    @DisplayName("equal values give equal objects and hash codes")
    void shouldCompareByValue() {
        final Base subject = create();
        final Base other = create();
        assertEquals(subject, other);
        assertEquals(subject.hashCode(), other.hashCode());
    }

    private static int aValue() {
        return 1;
    }

    private static Base create() {
        return new Base(aValue());
    }

    /// Asserts that two values are equal; arrays by their content.
    private static void assertValue(final @Nullable Object expected, final @Nullable Object actual) {
        if (expected instanceof byte[] bytes && actual instanceof byte[] other) {
            assertArrayEquals(bytes, other, () -> "expected " + Arrays.toString(bytes) + " but was " + Arrays.toString(other));
        } else {
            assertEquals(expected, actual);
        }
    }
}
