// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Circle`, generated from the specs.
@DisplayName("Circle")
class CircleTest {

    @Test
    @DisplayName("creates a Circle and returns the values")
    void shouldCreateAndReturnTheValues() {
        final Integer size = sizeValue();
        final Circle subject = new Circle(size);
        assertValue(size, subject.size());
    }

    @Test
    @DisplayName("rejects null for size")
    void shouldRejectNullSize() {
        assertThrows(NullPointerException.class, () -> new Circle((Integer) null));
    }

    @Test
    @DisplayName("size: accepts the minimum (-2147483648)")
    void shouldAcceptSizeAtMinimum() {
        final Integer value = Integer.MIN_VALUE;
        final Circle subject = new Circle(value);
        assertValue(value, subject.size());
    }

    @Test
    @DisplayName("size: accepts the maximum (2147483647)")
    void shouldAcceptSizeAtMaximum() {
        final Integer value = 2147483647;
        final Circle subject = new Circle(value);
        assertValue(value, subject.size());
    }

    @Test
    @DisplayName("equal values give equal objects and hash codes")
    void shouldCompareByValue() {
        final Circle subject = create();
        final Circle other = create();
        assertEquals(subject, other);
        assertEquals(subject.hashCode(), other.hashCode());
    }

    private static int sizeValue() {
        return 1;
    }

    private static Circle create() {
        return new Circle(sizeValue());
    }

    /// Asserts that two values are equal; arrays by their content.
    private static void assertValue(final @Nullable Object expected, final @Nullable Object actual) {
        if (expected instanceof byte[] bytes && actual instanceof byte[] other) {
            assertArrayEquals(bytes, other, () -> "expected " + Arrays.toString(bytes) + " but was " + Arrays.toString(other));
        } else {
            assertEquals(expected, actual);
        }
    }
}
