// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Derived`, generated from the specs.
@DisplayName("Derived")
class DerivedTest {

    @Test
    @DisplayName("creates a Derived and returns the values")
    void shouldCreateAndReturnTheValues() {
        final int a = aValue();
        final int b = bValue();
        final Derived subject = new Derived(a, b);
        assertValue(a, subject.a());
        assertValue(b, subject.b());
    }

    @Test
    @DisplayName("a: accepts the minimum (-2147483648)")
    void shouldAcceptAAtMinimum() {
        final int value = Integer.MIN_VALUE;
        final Derived subject = new Derived(value, bValue());
        assertValue(value, subject.a());
    }

    @Test
    @DisplayName("a: accepts the maximum (2147483647)")
    void shouldAcceptAAtMaximum() {
        final int value = 2147483647;
        final Derived subject = new Derived(value, bValue());
        assertValue(value, subject.a());
    }

    @Test
    @DisplayName("b: accepts the minimum (-2147483648)")
    void shouldAcceptBAtMinimum() {
        final int value = Integer.MIN_VALUE;
        final Derived subject = new Derived(aValue(), value);
        assertValue(value, subject.b());
    }

    @Test
    @DisplayName("b: accepts the maximum (2147483647)")
    void shouldAcceptBAtMaximum() {
        final int value = 2147483647;
        final Derived subject = new Derived(aValue(), value);
        assertValue(value, subject.b());
    }

    @Test
    @DisplayName("equal values give equal objects and hash codes")
    void shouldCompareByValue() {
        final Derived subject = create();
        final Derived other = create();
        assertEquals(subject, other);
        assertEquals(subject.hashCode(), other.hashCode());
    }

    private static int aValue() {
        return 1;
    }

    private static int bValue() {
        return 1;
    }

    private static Derived create() {
        return new Derived(aValue(), bValue());
    }

    /// Asserts that two values are equal; arrays by their content.
    private static void assertValue(final @Nullable Object expected, final @Nullable Object actual) {
        if (expected instanceof byte[] bytes && actual instanceof byte[] other) {
            assertArrayEquals(bytes, other, () -> "expected " + Arrays.toString(bytes) + " but was " + Arrays.toString(other));
        } else {
            assertEquals(expected, actual);
        }
    }
}
