// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Hash`, generated from the specs.
@DisplayName("Hash")
class HashTest {

    @Test
    @DisplayName("creates a Hash and returns the values")
    void shouldCreateAndReturnTheValues() {
        final byte[] valueArgument = valueValue();
        final Hash subject = new Hash(valueArgument);
        assertValue(valueArgument, subject.value());
    }

    @Test
    @DisplayName("rejects null for value")
    void shouldRejectNullValue() {
        assertThrows(NullPointerException.class, () -> new Hash((byte[]) null));
    }

    @Test
    @DisplayName("the constructor copies value; the accessor returns a copy")
    void shouldCopyValueIn() {
        final byte[] value = valueValue();
        final byte[] expected = value.clone();
        final Hash subject = new Hash(value);
        value[0] = (byte) (value[0] + 1);
        assertValue(expected, subject.value());
        final byte[] returned = subject.value();
        assertNotNull(returned);
        returned[0] = (byte) (returned[0] + 1);
        assertValue(expected, subject.value());
    }

    @Test
    @DisplayName("equal values give equal objects and hash codes")
    void shouldCompareByValue() {
        final Hash subject = create();
        final Hash other = create();
        assertEquals(subject, other);
        assertEquals(subject.hashCode(), other.hashCode());
    }

    @Test
    @DisplayName("toString() can be called and returns a value")
    void shouldCallToString() {
        assertNotNull(create().toString());
    }

    private static byte[] valueValue() {
        return new byte[] {1, 2, 3};
    }

    private static Hash create() {
        return new Hash(valueValue());
    }

    /// Asserts that two values are equal; arrays by their content.
    private static void assertValue(final @Nullable Object expected, final @Nullable Object actual) {
        if (expected instanceof byte[] bytes && actual instanceof byte[] other) {
            assertArrayEquals(bytes, other, () -> "expected " + Arrays.toString(bytes) + " but was " + Arrays.toString(other));
        } else {
            assertEquals(expected, actual);
        }
    }
}
