// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;

/// Tests of `Listing`, generated from the specs.
///
/// Not generated:
/// - no valid value for `entity` of Listing: constructor, attribute and method tests
@DisplayName("Listing")
class ListingTest {
}
