// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Address`, generated from the specs.
@DisplayName("Address")
class AddressTest {

    @Test
    @DisplayName("creates an Address and returns the values")
    void shouldCreateAndReturnTheValues() {
        final String street = streetValue();
        final @Nullable String zip = zipValue();
        final @Nullable String website = websiteValue();
        final String map = mapValue();
        final Address subject = new Address(street, zip, website, map);
        assertValue(street, subject.street());
        assertValue(zip, subject.zip());
        assertValue(website, subject.website());
        assertValue(map, subject.map());
    }

    @Test
    @DisplayName("rejects null for street")
    void shouldRejectNullStreet() {
        assertThrows(NullPointerException.class, () -> new Address((String) null, zipValue(), websiteValue(), mapValue()));
    }

    @Test
    @DisplayName("street: accepts a value with the minimum length")
    void shouldAcceptStreetAtMinimumLength() {
        final String value = "v";
        final Address subject = new Address(value, zipValue(), websiteValue(), mapValue());
        assertValue(value, subject.street());
    }

    @Test
    @DisplayName("street: rejects a value shorter than the minimum length")
    void shouldRejectStreetBelowMinimumLength() {
        assertThrows(IllegalArgumentException.class, () -> new Address("", zipValue(), websiteValue(), mapValue()));
    }

    @Test
    @DisplayName("street: accepts a value with the maximum length")
    void shouldAcceptStreetAtMaximumLength() {
        final String value = "valueaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
        final Address subject = new Address(value, zipValue(), websiteValue(), mapValue());
        assertValue(value, subject.street());
    }

    @Test
    @DisplayName("street: rejects a value longer than the maximum length")
    void shouldRejectStreetAboveMaximumLength() {
        assertThrows(IllegalArgumentException.class, () -> new Address("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", zipValue(), websiteValue(), mapValue()));
    }

    @Test
    @DisplayName("zip: rejects a value that does not match the pattern")
    void shouldRejectZipNotMatchingThePattern() {
        assertThrows(IllegalArgumentException.class, () -> new Address(streetValue(), "", websiteValue(), mapValue()));
    }

    @Test
    @DisplayName("website: rejects a value that is no URL")
    void shouldRejectWebsiteThatIsNoUrl() {
        assertThrows(IllegalArgumentException.class, () -> new Address(streetValue(), zipValue(), "not a url", mapValue()));
    }

    @Test
    @DisplayName("rejects null for map")
    void shouldRejectNullMap() {
        assertThrows(NullPointerException.class, () -> new Address(streetValue(), zipValue(), websiteValue(), (String) null));
    }

    @Test
    @DisplayName("map: rejects a value that is no URL")
    void shouldRejectMapThatIsNoUrl() {
        assertThrows(IllegalArgumentException.class, () -> new Address(streetValue(), zipValue(), websiteValue(), "not a url"));
    }

    @Test
    @DisplayName("equal values give equal objects and hash codes")
    void shouldCompareByValue() {
        final Address subject = create();
        final Address other = create();
        assertEquals(subject, other);
        assertEquals(subject.hashCode(), other.hashCode());
    }

    private static String streetValue() {
        return "value";
    }

    private static String zipValue() {
        return "00000";
    }

    private static String websiteValue() {
        return "https://example.com/v0";
    }

    private static String mapValue() {
        return "https://example.com/v0";
    }

    private static Address create() {
        return new Address(streetValue(), zipValue(), websiteValue(), mapValue());
    }

    /// Asserts that two values are equal; arrays by their content.
    private static void assertValue(final @Nullable Object expected, final @Nullable Object actual) {
        if (expected instanceof byte[] bytes && actual instanceof byte[] other) {
            assertArrayEquals(bytes, other, () -> "expected " + Arrays.toString(bytes) + " but was " + Arrays.toString(other));
        } else {
            assertEquals(expected, actual);
        }
    }
}
