// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Attachment`, generated from the specs.
@DisplayName("Attachment")
class AttachmentTest {

    @Test
    @DisplayName("creates an Attachment and returns the values")
    void shouldCreateAndReturnTheValues() {
        final byte[] content = contentValue();
        final byte @Nullable [] checksum = checksumValue();
        final double weight = weightValue();
        final @Nullable Integer count = countValue();
        final Attachment subject = new Attachment(content, checksum, weight, count);
        assertValue(content, subject.content());
        assertValue(checksum, subject.checksum());
        assertValue(weight, subject.weight());
        assertValue(count, subject.count());
    }

    @Test
    @DisplayName("rejects null for content")
    void shouldRejectNullContent() {
        assertThrows(NullPointerException.class, () -> new Attachment((byte[]) null, checksumValue(), weightValue(), countValue()));
    }

    @Test
    @DisplayName("content: accepts the minimum number of elements")
    void shouldAcceptContentAtMinimumSize() {
        final byte[] value = new byte[] {1};
        final Attachment subject = new Attachment(value, checksumValue(), weightValue(), countValue());
        assertValue(value, subject.content());
    }

    @Test
    @DisplayName("content: rejects fewer elements than the minimum")
    void shouldRejectContentBelowMinimumSize() {
        assertThrows(IllegalArgumentException.class, () -> new Attachment(new byte[0], checksumValue(), weightValue(), countValue()));
    }

    @Test
    @DisplayName("the constructor copies content; the accessor returns a copy")
    void shouldCopyContentIn() {
        final byte[] value = contentValue();
        final byte[] expected = value.clone();
        final Attachment subject = new Attachment(value, checksumValue(), weightValue(), countValue());
        value[0] = (byte) (value[0] + 1);
        assertValue(expected, subject.content());
        final byte[] returned = subject.content();
        assertNotNull(returned);
        returned[0] = (byte) (returned[0] + 1);
        assertValue(expected, subject.content());
    }

    @Test
    @DisplayName("the constructor copies checksum; the accessor returns a copy")
    void shouldCopyChecksumIn() {
        final byte[] value = checksumValue();
        final byte[] expected = value.clone();
        final Attachment subject = new Attachment(contentValue(), value, weightValue(), countValue());
        value[0] = (byte) (value[0] + 1);
        assertValue(expected, subject.checksum());
        final byte[] returned = subject.checksum();
        assertNotNull(returned);
        returned[0] = (byte) (returned[0] + 1);
        assertValue(expected, subject.checksum());
    }

    @Test
    @DisplayName("count: accepts the minimum (-2147483648)")
    void shouldAcceptCountAtMinimum() {
        final @Nullable Integer value = Integer.MIN_VALUE;
        final Attachment subject = new Attachment(contentValue(), checksumValue(), weightValue(), value);
        assertValue(value, subject.count());
    }

    @Test
    @DisplayName("count: accepts the maximum (2147483647)")
    void shouldAcceptCountAtMaximum() {
        final @Nullable Integer value = 2147483647;
        final Attachment subject = new Attachment(contentValue(), checksumValue(), weightValue(), value);
        assertValue(value, subject.count());
    }

    @Test
    @DisplayName("equal values give equal objects and hash codes")
    void shouldCompareByValue() {
        final Attachment subject = create();
        final Attachment other = create();
        assertEquals(subject, other);
        assertEquals(subject.hashCode(), other.hashCode());
    }

    private static byte[] contentValue() {
        return new byte[] {1, 2, 3};
    }

    private static byte[] checksumValue() {
        return new byte[] {1, 2, 3};
    }

    private static double weightValue() {
        return 1.5;
    }

    private static int countValue() {
        return 1;
    }

    private static Attachment create() {
        return new Attachment(contentValue(), checksumValue(), weightValue(), countValue());
    }

    /// Asserts that two values are equal; arrays by their content.
    private static void assertValue(final @Nullable Object expected, final @Nullable Object actual) {
        if (expected instanceof byte[] bytes && actual instanceof byte[] other) {
            assertArrayEquals(bytes, other, () -> "expected " + Arrays.toString(bytes) + " but was " + Arrays.toString(other));
        } else {
            assertEquals(expected, actual);
        }
    }
}
