// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import org.hiero.shop.money.Money;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Cart`, generated from the specs.
@SuppressWarnings("deprecation")
@DisplayName("Cart")
class CartTest {

    @Test
    @DisplayName("creates a Cart and returns the values")
    void shouldCreateAndReturnTheValues() {
        final List<String> items = itemsValue();
        final Set<String> coupons = couponsValue();
        final Map<String, String> notes = notesValue();
        final int quantity = quantityValue();
        final @Nullable Integer discount = discountValue();
        final boolean legacy = legacyValue();
        final Category category = categoryValue();
        final Money total = totalValue();
        final Cart<String> subject = new Cart<>(items, coupons, notes, quantity, discount, legacy, category, total);
        assertValue(items, subject.items());
        assertValue(coupons, subject.coupons());
        assertValue(notes, subject.notes());
        assertValue(quantity, subject.quantity());
        assertValue(discount, subject.discount());
        assertValue(legacy, subject.legacy());
        assertValue(category, subject.category());
        assertValue(total, subject.total());
    }

    @Test
    @DisplayName("creates a Cart with the default values")
    void shouldCreateWithTheDefaultValues() {
        final Cart<String> subject = new Cart<>(itemsValue(), notesValue(), discountValue(), legacyValue(), categoryValue(), totalValue());
        assertValue(Set.of(), subject.coupons());
        assertValue(1, subject.quantity());
    }

    @Test
    @DisplayName("rejects null for items")
    void shouldRejectNullItems() {
        assertThrows(NullPointerException.class, () -> new Cart<>((List<String>) null, couponsValue(), notesValue(), quantityValue(), discountValue(), legacyValue(), categoryValue(), totalValue()));
    }

    @Test
    @DisplayName("items: accepts the minimum number of elements")
    void shouldAcceptItemsAtMinimumSize() {
        final List<String> value = List.of("value");
        final Cart<String> subject = new Cart<>(value, couponsValue(), notesValue(), quantityValue(), discountValue(), legacyValue(), categoryValue(), totalValue());
        assertValue(value, subject.items());
    }

    @Test
    @DisplayName("items: rejects fewer elements than the minimum")
    void shouldRejectItemsBelowMinimumSize() {
        assertThrows(IllegalArgumentException.class, () -> new Cart<>(List.of(), couponsValue(), notesValue(), quantityValue(), discountValue(), legacyValue(), categoryValue(), totalValue()));
    }

    @Test
    @DisplayName("items: accepts the maximum number of elements")
    void shouldAcceptItemsAtMaximumSize() {
        final List<String> value = List.of("value", "value1", "value2", "value3", "value4", "value5", "value6", "value7", "value8", "value9", "value10", "value11", "value12", "value13", "value14", "value15", "value16", "value17", "value18", "value19", "value20", "value21", "value22", "value23", "value24", "value25", "value26", "value27", "value28", "value29", "value30", "value31", "value32", "value33", "value34", "value35", "value36", "value37", "value38", "value39", "value40", "value41", "value42", "value43", "value44", "value45", "value46", "value47", "value48", "value49", "value50", "value51", "value52", "value53", "value54", "value55", "value56", "value57", "value58", "value59", "value60", "value61", "value62", "value63", "value64", "value65", "value66", "value67", "value68", "value69", "value70", "value71", "value72", "value73", "value74", "value75", "value76", "value77", "value78", "value79", "value80", "value81", "value82", "value83", "value84", "value85", "value86", "value87", "value88", "value89", "value90", "value91", "value92", "value93", "value94", "value95", "value96", "value97", "value98", "value99");
        final Cart<String> subject = new Cart<>(value, couponsValue(), notesValue(), quantityValue(), discountValue(), legacyValue(), categoryValue(), totalValue());
        assertValue(value, subject.items());
    }

    @Test
    @DisplayName("items: rejects more elements than the maximum")
    void shouldRejectItemsAboveMaximumSize() {
        assertThrows(IllegalArgumentException.class, () -> new Cart<>(List.of("value", "value1", "value2", "value3", "value4", "value5", "value6", "value7", "value8", "value9", "value10", "value11", "value12", "value13", "value14", "value15", "value16", "value17", "value18", "value19", "value20", "value21", "value22", "value23", "value24", "value25", "value26", "value27", "value28", "value29", "value30", "value31", "value32", "value33", "value34", "value35", "value36", "value37", "value38", "value39", "value40", "value41", "value42", "value43", "value44", "value45", "value46", "value47", "value48", "value49", "value50", "value51", "value52", "value53", "value54", "value55", "value56", "value57", "value58", "value59", "value60", "value61", "value62", "value63", "value64", "value65", "value66", "value67", "value68", "value69", "value70", "value71", "value72", "value73", "value74", "value75", "value76", "value77", "value78", "value79", "value80", "value81", "value82", "value83", "value84", "value85", "value86", "value87", "value88", "value89", "value90", "value91", "value92", "value93", "value94", "value95", "value96", "value97", "value98", "value99", "value100"), couponsValue(), notesValue(), quantityValue(), discountValue(), legacyValue(), categoryValue(), totalValue()));
    }

    @Test
    @DisplayName("the constructor copies items; the accessor returns an unmodifiable collection")
    void shouldCopyItemsIn() {
        final List<String> value = new ArrayList<>(itemsValue());
        final List<String> expected = List.copyOf(value);
        final Cart<String> subject = new Cart<>(value, couponsValue(), notesValue(), quantityValue(), discountValue(), legacyValue(), categoryValue(), totalValue());
        value.clear();
        assertValue(expected, subject.items());
        assertThrows(UnsupportedOperationException.class, () -> Objects.requireNonNull(subject.items()).clear());
    }

    @Test
    @DisplayName("rejects null for coupons")
    void shouldRejectNullCoupons() {
        assertThrows(NullPointerException.class, () -> new Cart<>(itemsValue(), (Set<String>) null, notesValue(), quantityValue(), discountValue(), legacyValue(), categoryValue(), totalValue()));
    }

    @Test
    @DisplayName("the constructor copies coupons; the accessor returns an unmodifiable collection")
    void shouldCopyCouponsIn() {
        final Set<String> value = new LinkedHashSet<>(couponsValue());
        final Set<String> expected = Set.copyOf(value);
        final Cart<String> subject = new Cart<>(itemsValue(), value, notesValue(), quantityValue(), discountValue(), legacyValue(), categoryValue(), totalValue());
        value.clear();
        assertValue(expected, subject.coupons());
        assertThrows(UnsupportedOperationException.class, () -> Objects.requireNonNull(subject.coupons()).clear());
    }

    @Test
    @DisplayName("rejects null for notes")
    void shouldRejectNullNotes() {
        assertThrows(NullPointerException.class, () -> new Cart<>(itemsValue(), couponsValue(), (Map<String, String>) null, quantityValue(), discountValue(), legacyValue(), categoryValue(), totalValue()));
    }

    @Test
    @DisplayName("the constructor copies notes; the accessor returns an unmodifiable map")
    void shouldCopyNotesIn() {
        final Map<String, String> value = new LinkedHashMap<>(notesValue());
        final Map<String, String> expected = Map.copyOf(value);
        final Cart<String> subject = new Cart<>(itemsValue(), couponsValue(), value, quantityValue(), discountValue(), legacyValue(), categoryValue(), totalValue());
        value.clear();
        assertValue(expected, subject.notes());
        assertThrows(UnsupportedOperationException.class, () -> Objects.requireNonNull(subject.notes()).clear());
    }

    @Test
    @DisplayName("quantity: accepts the minimum (1)")
    void shouldAcceptQuantityAtMinimum() {
        final int value = 1;
        final Cart<String> subject = new Cart<>(itemsValue(), couponsValue(), notesValue(), value, discountValue(), legacyValue(), categoryValue(), totalValue());
        assertValue(value, subject.quantity());
    }

    @Test
    @DisplayName("quantity: accepts the maximum (10)")
    void shouldAcceptQuantityAtMaximum() {
        final int value = 10;
        final Cart<String> subject = new Cart<>(itemsValue(), couponsValue(), notesValue(), value, discountValue(), legacyValue(), categoryValue(), totalValue());
        assertValue(value, subject.quantity());
    }

    @Test
    @DisplayName("quantity: rejects a value below the minimum (0)")
    void shouldRejectQuantityBelowMinimum() {
        assertThrows(IllegalArgumentException.class, () -> new Cart<>(itemsValue(), couponsValue(), notesValue(), 0, discountValue(), legacyValue(), categoryValue(), totalValue()));
    }

    @Test
    @DisplayName("quantity: rejects a value above the maximum (11)")
    void shouldRejectQuantityAboveMaximum() {
        assertThrows(IllegalArgumentException.class, () -> new Cart<>(itemsValue(), couponsValue(), notesValue(), 11, discountValue(), legacyValue(), categoryValue(), totalValue()));
    }

    @Test
    @DisplayName("discount: accepts the minimum (0)")
    void shouldAcceptDiscountAtMinimum() {
        final @Nullable Integer value = 0;
        final Cart<String> subject = new Cart<>(itemsValue(), couponsValue(), notesValue(), quantityValue(), value, legacyValue(), categoryValue(), totalValue());
        assertValue(value, subject.discount());
    }

    @Test
    @DisplayName("discount: accepts the maximum (2147483647)")
    void shouldAcceptDiscountAtMaximum() {
        final @Nullable Integer value = 2147483647;
        final Cart<String> subject = new Cart<>(itemsValue(), couponsValue(), notesValue(), quantityValue(), value, legacyValue(), categoryValue(), totalValue());
        assertValue(value, subject.discount());
    }

    @Test
    @DisplayName("discount: rejects a value below the minimum (-1)")
    void shouldRejectDiscountBelowMinimum() {
        assertThrows(IllegalArgumentException.class, () -> new Cart<>(itemsValue(), couponsValue(), notesValue(), quantityValue(), -1, legacyValue(), categoryValue(), totalValue()));
    }

    @Test
    @DisplayName("rejects null for category")
    void shouldRejectNullCategory() {
        assertThrows(NullPointerException.class, () -> new Cart<>(itemsValue(), couponsValue(), notesValue(), quantityValue(), discountValue(), legacyValue(), (Category) null, totalValue()));
    }

    @Test
    @DisplayName("rejects null for total")
    void shouldRejectNullTotal() {
        assertThrows(NullPointerException.class, () -> new Cart<>(itemsValue(), couponsValue(), notesValue(), quantityValue(), discountValue(), legacyValue(), categoryValue(), (Money) null));
    }

    @Test
    @DisplayName("equal values give equal objects and hash codes")
    void shouldCompareByValue() {
        final Cart<String> subject = create();
        final Cart<String> other = create();
        assertEquals(subject, other);
        assertEquals(subject.hashCode(), other.hashCode());
    }

    @Test
    @DisplayName("sum() can be called and returns a value")
    void shouldCallSum() {
        assertNotNull(create().sum());
    }

    @Test
    @DisplayName("empty() can be called and returns a value")
    void shouldCallEmpty() {
        assertNotNull(Cart.empty());
    }

    private static List<String> itemsValue() {
        return List.of("value");
    }

    private static Set<String> couponsValue() {
        return Set.of("value");
    }

    private static Map<String, String> notesValue() {
        return Map.ofEntries(Map.entry("value", "value"));
    }

    private static int quantityValue() {
        return 1;
    }

    private static int discountValue() {
        return 1;
    }

    private static boolean legacyValue() {
        return true;
    }

    private static Category categoryValue() {
        return Category.FOOD;
    }

    private static Money totalValue() {
        return new Money(new BigInteger("1"), null);
    }

    private static Cart<String> create() {
        return new Cart<>(itemsValue(), couponsValue(), notesValue(), quantityValue(), discountValue(), legacyValue(), categoryValue(), totalValue());
    }

    /// Asserts that two values are equal; arrays by their content.
    private static void assertValue(final @Nullable Object expected, final @Nullable Object actual) {
        if (expected instanceof byte[] bytes && actual instanceof byte[] other) {
            assertArrayEquals(bytes, other, () -> "expected " + Arrays.toString(bytes) + " but was " + Arrays.toString(other));
        } else {
            assertEquals(expected, actual);
        }
    }
}
