// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import java.util.NoSuchElementException;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Category`, generated from the specs.
@SuppressWarnings("deprecation")
@DisplayName("Category")
class CategoryTest {

    @Test
    @DisplayName("the constants have the attribute values of the specs")
    void shouldProvideTheAttributesOfTheConstants() {
        assertValue((byte) 1, Category.FOOD.code());
        assertValue("Food", Category.FOOD.label());
        assertValue((byte) 2, Category.OTHER.code());
        assertValue(null, Category.OTHER.label());
        assertValue((byte) 3, Category.LEGACY.code());
        assertValue("Legacy \"old\"", Category.LEGACY.label());
        assertValue((byte) 4, Category.MISC.code());
        assertValue("Misc", Category.MISC.label());
    }

    @Test
    @DisplayName("isFood() can be called")
    void shouldCallIsFood() {
        Category.FOOD.isFood();
    }

    @Test
    @DisplayName("byCode(code) can be called and returns a value (only NoSuchElementException may occur)")
    void shouldCallByCode() throws Exception {
        try {
            assertNotNull(Category.byCode(codeValue()));
        } catch (final Exception e) {
            if (!(e instanceof NoSuchElementException)) {
                throw e;
            }
        }
    }

    private static byte codeValue() {
        return (byte) 1;
    }

    /// Asserts that two values are equal; arrays by their content.
    private static void assertValue(final @Nullable Object expected, final @Nullable Object actual) {
        if (expected instanceof byte[] bytes && actual instanceof byte[] other) {
            assertArrayEquals(bytes, other, () -> "expected " + Arrays.toString(bytes) + " but was " + Arrays.toString(other));
        } else {
            assertEquals(expected, actual);
        }
    }
}
