// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Arrays;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Counter`, generated from the specs.
@DisplayName("Counter")
class CounterTest {

    @Test
    @DisplayName("creates a Counter and returns the values")
    void shouldCreateAndReturnTheValues() {
        final int valueArgument = valueValue();
        final Counter subject = new Counter(valueArgument);
        assertValue(valueArgument, subject.value());
    }

    @Test
    @DisplayName("value: accepts the minimum (-2147483648)")
    void shouldAcceptValueAtMinimum() {
        final int value = Integer.MIN_VALUE;
        final Counter subject = new Counter(value);
        assertValue(value, subject.value());
    }

    @Test
    @DisplayName("value: accepts the maximum (2147483647)")
    void shouldAcceptValueAtMaximum() {
        final int value = 2147483647;
        final Counter subject = new Counter(value);
        assertValue(value, subject.value());
    }

    @Test
    @DisplayName("setValue changes value and returns the object")
    void shouldSetValue() {
        final Counter subject = create();
        final int value = valueOtherValue();
        assertSame(subject, subject.setValue(value));
        assertValue(value, subject.value());
    }

    @Test
    @DisplayName("setValue accepts the minimum (-2147483648)")
    void shouldSetValueAtMinimum() {
        final Counter subject = create();
        final int value = Integer.MIN_VALUE;
        subject.setValue(value);
        assertValue(value, subject.value());
    }

    @Test
    @DisplayName("setValue accepts the maximum (2147483647)")
    void shouldSetValueAtMaximum() {
        final Counter subject = create();
        final int value = 2147483647;
        subject.setValue(value);
        assertValue(value, subject.value());
    }

    private static int valueValue() {
        return 1;
    }

    private static Counter create() {
        return new Counter(valueValue());
    }

    private static int valueOtherValue() {
        return 2;
    }

    /// Asserts that two values are equal; arrays by their content.
    private static void assertValue(final @Nullable Object expected, final @Nullable Object actual) {
        if (expected instanceof byte[] bytes && actual instanceof byte[] other) {
            assertArrayEquals(bytes, other, () -> "expected " + Arrays.toString(bytes) + " but was " + Arrays.toString(other));
        } else {
            assertEquals(expected, actual);
        }
    }
}
