// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Printer`, generated from the specs.
@DisplayName("Printer")
class PrinterTest {

    @Test
    @DisplayName("creates a Printer and returns the values")
    void shouldCreateAndReturnTheValues() {
        final Printer subject = new Printer();
    }

    @Test
    @DisplayName("print() can be called")
    void shouldCallPrint() {
        create().print();
    }

    private static Printer create() {
        return new Printer();
    }
}
