// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import java.math.BigInteger;
import java.util.Arrays;
import org.hiero.shop.money.Money;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Product`, generated from the specs.
///
/// Not generated:
/// - no valid arguments for `sameAs(shop.Entity<$$O>)`
@DisplayName("Product")
class ProductTest {

    @Test
    @DisplayName("creates a Product and returns the values")
    void shouldCreateAndReturnTheValues() {
        final Long id = idValue();
        final String name = nameValue();
        final Money price = priceValue();
        final Product subject = new Product(id, name, price);
        assertValue(id, subject.id());
        assertValue(name, subject.name());
        assertValue(price, subject.price());
    }

    @Test
    @DisplayName("rejects null for id")
    void shouldRejectNullId() {
        assertThrows(NullPointerException.class, () -> new Product((Long) null, nameValue(), priceValue()));
    }

    @Test
    @DisplayName("id: accepts the minimum (-9223372036854775808)")
    void shouldAcceptIdAtMinimum() {
        final Long value = -9223372036854775808L;
        final Product subject = new Product(value, nameValue(), priceValue());
        assertValue(value, subject.id());
    }

    @Test
    @DisplayName("id: accepts the maximum (9223372036854775807)")
    void shouldAcceptIdAtMaximum() {
        final Long value = 9223372036854775807L;
        final Product subject = new Product(value, nameValue(), priceValue());
        assertValue(value, subject.id());
    }

    @Test
    @DisplayName("rejects null for name")
    void shouldRejectNullName() {
        assertThrows(NullPointerException.class, () -> new Product(idValue(), (String) null, priceValue()));
    }

    @Test
    @DisplayName("name: accepts a value with the maximum length")
    void shouldAcceptNameAtMaximumLength() {
        final String value = "valueaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
        final Product subject = new Product(idValue(), value, priceValue());
        assertValue(value, subject.name());
    }

    @Test
    @DisplayName("name: rejects a value longer than the maximum length")
    void shouldRejectNameAboveMaximumLength() {
        assertThrows(IllegalArgumentException.class, () -> new Product(idValue(), "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", priceValue()));
    }

    @Test
    @DisplayName("rejects null for price")
    void shouldRejectNullPrice() {
        assertThrows(NullPointerException.class, () -> new Product(idValue(), nameValue(), (Money) null));
    }

    @Test
    @DisplayName("equal values give equal objects and hash codes")
    void shouldCompareByValue() {
        final Product subject = create();
        final Product other = create();
        assertEquals(subject, other);
        assertEquals(subject.hashCode(), other.hashCode());
    }

    @Test
    @DisplayName("related(limit) can be called and returns a value")
    void shouldCallRelated() {
        assertNotNull(create().related(limitValue()));
    }

    private static long idValue() {
        return 1L;
    }

    private static String nameValue() {
        return "value";
    }

    private static Money priceValue() {
        return new Money(new BigInteger("1"), null);
    }

    private static Product create() {
        return new Product(idValue(), nameValue(), priceValue());
    }

    private static int limitValue() {
        return 1;
    }

    /// Asserts that two values are equal; arrays by their content.
    private static void assertValue(final @Nullable Object expected, final @Nullable Object actual) {
        if (expected instanceof byte[] bytes && actual instanceof byte[] other) {
            assertArrayEquals(bytes, other, () -> "expected " + Arrays.toString(bytes) + " but was " + Arrays.toString(other));
        } else {
            assertEquals(expected, actual);
        }
    }
}
