// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Shape`, generated from the specs.
@DisplayName("Shape")
class ShapeTest {

    @Test
    @DisplayName("unit() can be called and returns a value")
    void shouldCallUnit() {
        assertNotNull(Shape.unit());
    }
}
