// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `ShopFactory`, generated from the specs.
@DisplayName("ShopFactory")
class ShopFactoryTest {

    @Test
    @DisplayName("create(name, tags) can be called and returns a value")
    void shouldCallCreate() {
        assertNotNull(ShopFactory.create(nameValue(), tagsValue()));
    }

    @Test
    @DisplayName("create rejects null for name")
    void shouldRejectNullNameInCreate() {
        assertThrows(NullPointerException.class, () -> ShopFactory.create((String) null, tagsValue()));
    }

    private static String nameValue() {
        return "value";
    }

    private static String tagsValue() {
        return "value";
    }
}
