// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

package org.hiero.shop;

import static org.junit.jupiter.api.Assertions.*;

import java.math.BigInteger;
import java.util.Arrays;
import java.util.concurrent.TimeoutException;
import org.hiero.shop.money.Money;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/// Tests of `Square`, generated from the specs.
@DisplayName("Square")
class SquareTest {

    @Test
    @DisplayName("creates a Square and returns the values")
    void shouldCreateAndReturnTheValues() {
        final @Nullable Integer size = sizeValue();
        final Money price = priceValue();
        final Square subject = new Square(size, price);
        assertValue(size, subject.size());
        assertValue(price, subject.price());
    }

    @Test
    @DisplayName("size: accepts the minimum (-2147483648)")
    void shouldAcceptSizeAtMinimum() {
        final @Nullable Integer value = Integer.MIN_VALUE;
        final Square subject = new Square(value, priceValue());
        assertValue(value, subject.size());
    }

    @Test
    @DisplayName("size: accepts the maximum (2147483647)")
    void shouldAcceptSizeAtMaximum() {
        final @Nullable Integer value = 2147483647;
        final Square subject = new Square(value, priceValue());
        assertValue(value, subject.size());
    }

    @Test
    @DisplayName("rejects null for price")
    void shouldRejectNullPrice() {
        assertThrows(NullPointerException.class, () -> new Square(sizeValue(), (Money) null));
    }

    @Test
    @DisplayName("equal values give equal objects and hash codes")
    void shouldCompareByValue() {
        final Square subject = create();
        final Square other = create();
        assertEquals(subject, other);
        assertEquals(subject.hashCode(), other.hashCode());
    }

    @Test
    @DisplayName("gross(taxRate) can be called and returns a value (only PricingException, TimeoutException may occur)")
    void shouldCallGross() throws Exception {
        try {
            assertNotNull(create().gross(taxRateValue()));
        } catch (final Exception e) {
            if (!(e instanceof PricingException || e instanceof TimeoutException)) {
                throw e;
            }
        }
    }

    private static int sizeValue() {
        return 1;
    }

    private static Money priceValue() {
        return new Money(new BigInteger("1"), null);
    }

    private static Square create() {
        return new Square(sizeValue(), priceValue());
    }

    private static double taxRateValue() {
        return 1.5;
    }

    /// Asserts that two values are equal; arrays by their content.
    private static void assertValue(final @Nullable Object expected, final @Nullable Object actual) {
        if (expected instanceof byte[] bytes && actual instanceof byte[] other) {
            assertArrayEquals(bytes, other, () -> "expected " + Arrays.toString(bytes) + " but was " + Arrays.toString(other));
        } else {
            assertEquals(expected, actual);
        }
    }
}
