// Generated by metalang from the Hiero SDK V3 specs. Do not edit.

import org.jspecify.annotations.NullMarked;

/// Module `org.hiero.shop` of the Hiero SDK.
///
/// Packages:
/// - `org.hiero.shop`
@NullMarked
module org.hiero.shop {
    requires transitive org.hiero.core;
    requires static transitive org.jspecify;

    exports org.hiero.shop;
}
